import { test, expect } from '@playwright/test';
import fs from 'node:fs';
import { evolutionFor, nextEvolution } from '../src/illustrations/sidekick.js';
import { renderScene } from '../src/illustrations/engine.js';
const chapters=Array.from({length:23},(_,i)=>JSON.parse(fs.readFileSync(new URL(`../src/chapters/${String(i+2).padStart(2,'0')}.json`,import.meta.url),'utf8')));
const gotoStep=async(page,step)=>{await page.locator(`.course-steps [data-go="${step}"]`).click();await expect(page).toHaveURL(new RegExp('/'+step+'$'));await expect(page.locator('#book-location')).not.toContainText('Chapter map')};

test('all 24 chapters are discoverable, searchable, and Chapter 1 is retained',async({page})=>{
 await page.goto('/fundamentals.html');await expect(page.locator('.chapter-card')).toHaveCount(24);await page.getByRole('searchbox').fill('pipeline');await expect(page.locator('.chapter-card:visible')).toHaveCount(1);await page.getByRole('button',{name:'Open chapter 11: Pipeline Architecture Style'}).click();await expect(page.locator('.chapter-overview h1')).toHaveText('Pipeline Architecture Style');await page.goBack();await expect(page.locator('.book-library')).toBeVisible();await page.locator('[data-open-chapter="1"]').click();await expect(page).toHaveURL(/chapter-one.html#map/);await expect(page.locator('#course-map')).toBeVisible();await page.getByRole('link',{name:'All chapters',exact:true}).click();await expect(page.locator('.chapter-card')).toHaveCount(24);
});

for(const chapter of chapters){
 test(`chapter ${chapter.number}: full five-stop learning journey and artifact`,async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/#chapter/${chapter.number}/map`);await expect(page.locator('.chapter-overview h1')).toHaveText(chapter.title);await expect(page.locator('.map-stop')).toHaveCount(5);
  await gotoStep(page,'intro');await expect(page.locator('.chapter-prose')).toContainText(chapter.summary);await page.locator('#book-next').click();await expect(page).toHaveURL(/\/explore$/);
  for(let i=0;i<chapter.concepts.length;i++)await page.locator(`[data-concept="${i}"]`).click();await expect(page.locator('#book-chapter-score')).toHaveText('20 / 100 chapter XP');await expect(page.locator('#chapter-concept')).toContainText(chapter.concepts.at(-1).body);
  await gotoStep(page,'scenario');if(chapter.number===11){await page.locator('#lab-guard').check();await page.locator('#book-next').click();await expect(page.locator('.lab-visual')).toHaveAttribute('data-outcome','rejected');await page.locator('[value="good"]').check();await page.locator('#book-next').click();await expect(page.locator('.lab-visual')).toHaveAttribute('data-outcome','stored');}else{await page.locator('[data-choice="0"]').click();await expect(page.locator('#decision-consequence')).toContainText(chapter.scenario.options[0].cost);await page.locator('[data-choice="1"]').click();}await expect(page.locator('#book-chapter-score')).toHaveText('40 / 100 chapter XP');
  await gotoStep(page,'quiz');for(let i=0;i<chapter.quiz.length;i++){await page.locator(`[data-answer="${chapter.quiz[i].answer}"]`).click();if(chapter.number===11)await page.locator('#book-next').click();await expect(page.locator('.quiz-feedback')).toContainText(chapter.quiz[i].explanation);await page.locator(chapter.number===11?'#book-next':'#next-reflection').click()};await expect(page.locator('.quiz-finish h2')).toContainText('3 of 3');await expect(page.locator('#book-chapter-score')).toHaveText('60 / 100 chapter XP');
  await gotoStep(page,'apply');for(let i=0;i<chapter.exercise.fields.length;i++)await page.locator(`[data-work="${i}"]`).fill(`Chapter ${chapter.number}: our team accepts this cost to meet a specific business goal.`);const pending=page.waitForEvent('download');await page.locator(chapter.number===11?'#book-next':'.chapter-workbook button[type="submit"]').click();const artifact=await pending;expect(artifact.suggestedFilename()).toBe(`chapter-${String(chapter.number).padStart(2,'0')}-reflection.md`);await expect(page.locator('#book-chapter-score')).toHaveText('100 / 100 chapter XP');await page.reload();await expect(page.locator('#book-chapter-score')).toHaveText('100 / 100 chapter XP');await expect(page.locator('[data-work="0"]')).toHaveValue(new RegExp(`Chapter ${chapter.number}`));expect(errors).toEqual([]);
 });
}

test('Pip thresholds span the book and depend on earned missions',()=>{
 expect([0,99,100,399,400,899,900,1599,1600,2399,2400].map(x=>evolutionFor(x).xp)).toEqual([0,0,100,100,400,400,900,900,1600,1600,2400]);expect(nextEvolution(100).xp).toBe(400);expect(nextEvolution(2400)).toBeNull();
});

test('chapter data has bounded sources, complete activities, and valid scene references',()=>{
 const source=JSON.parse(fs.readFileSync(new URL('../docs/chapters/source-index.json',import.meta.url),'utf8'));
 for(const ch of chapters){const bounds=source.find(x=>x.number===ch.number);expect(ch.source.startLine).toBe(bounds.startLine);expect(ch.source.endLine).toBe(bounds.endLine);expect(ch.concepts.length).toBeGreaterThanOrEqual(3);expect(ch.quiz).toHaveLength(3);expect(ch.misconceptions).toHaveLength(2);expect(ch.scenario.options).toHaveLength(2);for(const q of ch.quiz){expect(q.answer).toBeGreaterThanOrEqual(0);expect(q.answer).toBeLessThan(q.options.length)}const ids=new Set(ch.visual.nodes.map(n=>n.id));for(const step of ch.visual.steps)expect(ids.has(step.node)).toBe(true);expect(renderScene({title:ch.title,nodes:ch.visual.nodes.map((n,i)=>({...n,x:100+i*70,y:100+i*30})),edges:ch.visual.edges})).toContain('data-sequence');expect(fs.readFileSync(new URL(`../public/notes/chapter-${String(ch.number).padStart(2,'0')}.md`,import.meta.url),'utf8').split(/\s+/).length).toBeGreaterThan(450)}
});

test('logical scene progression, manual stepping and pause have distinct behavior',async({page})=>{
 await page.goto('/#chapter/11/intro');const svg=page.locator('[data-scene-player] svg');await expect(svg).toHaveAttribute('data-step','0');await expect(svg).toHaveAttribute('data-step','1',{timeout:5000});await page.locator('[data-scene-step="2"]').click();await expect(svg).toHaveAttribute('data-step','2');await expect(page.locator('[data-scene-player]')).toHaveAttribute('data-playing','false');await expect(page.locator('[data-scene-caption]')).toHaveText(chapters.find(c=>c.number===11).visual.steps[2].text);
 expect(await svg.locator('.iso-object').first().evaluate(e=>getComputedStyle(e).animationName)).toBe('iso-float-subject');expect(await svg.locator('.iso-traveler').first().evaluate(e=>getComputedStyle(e).animationPlayState)).toBe('paused');await page.locator('.motion-toggle').click();expect(await svg.locator('.iso-object').first().evaluate(e=>getComputedStyle(e).animationPlayState)).toBe('paused');
 await page.emulateMedia({reducedMotion:'reduce'});expect(await svg.locator('.iso-object').first().evaluate(e=>getComputedStyle(e).animationName)).toBe('none');await page.locator('[data-scene-step="0"]').click();await expect(svg).toHaveAttribute('data-step','0');
});

test('cross-chapter progress persists, skipping stays free, and mobile screens fit',async({page})=>{
 await page.setViewportSize({width:360,height:700});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/#chapter/24/map');await gotoStep(page,'quiz');await page.locator('#book-next').click();await expect(page.locator('.book-xp strong')).toHaveText('0 / 2,400 XP');await page.getByRole('button',{name:'All chapters'}).click();await page.locator('[data-open-chapter="14"]').click();await gotoStep(page,'scenario');await page.locator('[data-choice="0"]').click();await page.locator('[data-choice="1"]').click();await expect(page.locator('.book-xp strong')).toHaveText('20 / 2,400 XP');await page.reload();await expect(page.locator('.book-xp strong')).toHaveText('20 / 2,400 XP');await page.locator('[data-choice="0"]').click();await expect(page.locator('.book-xp strong')).toHaveText('20 / 2,400 XP');
 for(const width of [320,360,390,768]){await page.setViewportSize({width,height:700});for(const step of ['intro','explore','scenario','quiz','apply']){await gotoStep(page,step);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.locator('.course-stage').evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true);await expect(page.locator('#book-next')).toBeInViewport()}}
});

test('every one of the 50 reusable scenes visibly moves across actual frames',async({page})=>{
 test.setTimeout(60000);await page.emulateMedia({reducedMotion:'no-preference'});await page.goto('/illustrations.html');await expect(page.locator('#scene-choice option')).toHaveCount(50);const values=await page.locator('#scene-choice option').evaluateAll(options=>options.map(o=>o.value));expect(values).toHaveLength(50);
 for(const value of values){await page.locator('#scene-choice').selectOption(value);const object=page.locator('#scene-preview .iso-object').first();await expect.poll(()=>object.evaluate(e=>getComputedStyle(e).animationPlayState)).toBe('running');const positions=[];for(let frame=0;frame<3;frame++){positions.push((await object.boundingBox()).y);await page.waitForTimeout(150)}expect(Math.max(...positions)-Math.min(...positions),`${value} must visibly float`).toBeGreaterThan(.1);const paths=page.locator('#scene-preview .iso-edge');if(await paths.count())await expect(page.locator('#scene-preview .iso-traveler')).toHaveCount(await paths.count())}
});
