import {test,expect} from '@playwright/test';
import fs from 'node:fs';
const index=JSON.parse(fs.readFileSync(new URL('../docs/hard-parts/source-index.json',import.meta.url),'utf8'));
const chapters=index.map(c=>JSON.parse(fs.readFileSync(new URL(`../src/paths/hard-parts/chapters/${String(c.number).padStart(2,'0')}.json`,import.meta.url),'utf8')));
test('home presents both paths and preserves the original ledger across new-path work',async({page})=>{
 const original={version:1,chapters:{1:{missions:{explore:true,sort:true,lab:true,quiz:true,record:true},read:['system'],activity:{draft:['original note']}},11:{missions:{explore:true},read:['intro'],activity:{draft:['Do not overwrite my reflection'],concept:2}}}};
 await page.goto('/');await page.evaluate(value=>localStorage.setItem('fieldnotes-book-v1',JSON.stringify(value)),original);await page.reload();await expect(page.locator('.path-card')).toHaveCount(7);await expect(page.locator('.path-fundamentals')).toContainText('120 / 2,400 XP');await expect(page.locator('.path-hard-parts')).toContainText('0 / 1,500 XP');await page.locator('.path-hard-parts .primary').click();await expect(page.locator('.chapter-card')).toHaveCount(15);await page.locator('[data-open-chapter="1"]').click();await page.locator('[data-go="explore"]').click();await page.locator('[data-concept]').first().waitFor();for(const b of await page.locator('[data-concept]').all())await b.click();await expect(page.locator('#book-chapter-score')).toHaveText('20 / 100 chapter XP');await page.locator('[data-go="apply"]').click();await page.locator('[data-work="0"]').fill('A new reflection for the second book.');await page.getByRole('link',{name:'Learning paths'}).click();await expect(page.locator('.path-hard-parts')).toContainText('20 / 1,500 XP');await expect(page.locator('.home-xp')).toHaveText('140 XP across your paths');await page.locator('.path-hard-parts .primary').click();await expect(page).toHaveURL(/hard-parts.html#chapter\/1\/apply$/);await expect(page.locator('[data-work="0"]')).toHaveValue('A new reflection for the second book.');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('fieldnotes-book-v1')))).toEqual(original);
 await page.goto('/fundamentals.html#chapter/11/apply');await expect(page.locator('[data-work="0"]')).toHaveValue('Do not overwrite my reflection');await expect(page.locator('.book-xp strong')).toHaveText('120 / 2,400 XP');
});
for(const ch of chapters)test(`Hard Parts ${ch.number}: complete journey, earned XP, scoped artifact and reload`,async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`/hard-parts.html#chapter/${ch.number}/map`);await expect(page.locator('.chapter-overview h1')).toHaveText(ch.title);await expect(page.locator('.map-stop')).toHaveCount(5);await expect(page.locator('.chapter-notes')).toHaveAttribute('href',`/notes/hard-parts/chapter-${String(ch.number).padStart(2,'0')}.md`);
 await page.locator('[data-go="intro"]').click();await expect(page.locator('.chapter-prose')).toContainText(ch.summary);await page.locator('#book-next').click();await page.locator('[data-concept]').first().waitFor();for(const b of await page.locator('[data-concept]').all())await b.click();await expect(page.locator('#book-chapter-score')).toHaveText('20 / 100 chapter XP');await page.locator('#book-next').click();await page.locator('[data-choice="0"]').click();await expect(page.locator('#decision-consequence')).toContainText(ch.scenario.options[0].cost);await page.locator('[data-choice="1"]').click();await expect(page.locator('#book-chapter-score')).toHaveText('40 / 100 chapter XP');await page.locator('#book-next').click();for(const q of ch.quiz){await page.locator(`[data-answer="${q.answer}"]`).click();await page.locator('#book-next').click();await expect(page.locator('.quiz-feedback')).toContainText(q.explanation);await page.locator('#book-next').click()}await expect(page.locator('.quiz-finish h2')).toContainText('3 of 3');await page.locator('#book-next').click();await page.locator('[data-work]').first().waitFor();for(const field of await page.locator('[data-work]').all())await field.fill('We accept this coordination cost and will validate recovery with a failure test.');const pending=page.waitForEvent('download');await page.locator('#book-next').click();expect((await pending).suggestedFilename()).toBe(`hard-parts-chapter-${String(ch.number).padStart(2,'0')}-reflection.md`);await expect(page.locator('#book-chapter-score')).toHaveText('100 / 100 chapter XP');await page.reload();await expect(page.locator('#book-chapter-score')).toHaveText('100 / 100 chapter XP');await expect(page.locator('[data-work="0"]')).toHaveValue(/coordination cost/);expect(errors).toEqual([]);
});
test('source boundaries, lesson shape and notes cover all supplied chapters',()=>{
 expect(chapters).toHaveLength(15);for(const ch of chapters){const src=index.find(x=>x.number===ch.number);expect(ch.source.startLine).toBe(src.startLine);expect(ch.source.endLine).toBe(src.endLine);expect(ch.part).toBe(src.part);expect(ch.source.reference).toContain('text lines');expect(ch.concepts.length).toBeGreaterThanOrEqual(4);expect(ch.quiz).toHaveLength(3);expect(ch.misconceptions).toHaveLength(2);expect(ch.scenario.options).toHaveLength(2);for(const q of ch.quiz){expect(q.answer).toBeGreaterThanOrEqual(0);expect(q.answer).toBeLessThan(q.options.length)}const ids=new Set(ch.visual.nodes.map(n=>n.id));for(const step of ch.visual.steps)expect(ids.has(step.node)).toBe(true);for(const edge of ch.visual.edges){expect(ids.has(edge.from)).toBe(true);expect(ids.has(edge.to)).toBe(true)}const notes=fs.readFileSync(new URL(`../public/notes/hard-parts/chapter-${String(ch.number).padStart(2,'0')}.md`,import.meta.url),'utf8');expect(notes.split(/\s+/).length).toBeGreaterThan(450);}
});
test('mobile path selection, navigation, skipping and original deep links work',async({page})=>{
 for(const width of [320,390,768]){await page.setViewportSize({width,height:760});await page.goto('/');await expect(page.locator('.path-card:visible')).toHaveCount(7);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);for(const step of ['map','intro','explore','scenario','quiz','apply']){await page.goto('/hard-parts.html#chapter/12/'+step);await expect(page.locator('#book-location')).toContainText('Transactional Sagas');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(await page.locator('.course-stage').evaluate(e=>e.scrollWidth<=e.clientWidth)).toBe(true);if(step!=='map')await expect(page.locator('#book-next')).toBeInViewport()}}
 await page.locator('[data-go="quiz"]').click();await page.locator('#book-skip').click();await expect(page).toHaveURL(/apply$/);await expect(page.locator('#book-chapter-score')).toHaveText('0 / 100 chapter XP');await page.goto('/#chapter/11/intro');await expect(page).toHaveURL(/fundamentals.html#chapter\/11\/intro$/);await expect(page.locator('.book-intro')).toContainText('Pipeline');await page.goto('/#lesson/foundations');await expect(page).toHaveURL(/chapter-one.html#lesson\/foundations$/);
});
