import {downloadText} from '../downloads.js';
import '../style.css';
import './illustrations.css';
import './studio.css';
import { renderScene, renderFigure, palettes, primitiveDescriptions } from './engine.js';
import { sceneLibrary as baseLibrary } from './scenes.js';
import { chapterScene } from '../chapters/visuals.js';
const vocabulary={...primitiveDescriptions,block:'Generic element when no specific role applies',database:'Persistent store: cylinder',document:'Written record or agreement: page',gateway:'Admission check or access boundary: gate',person:'An individual stakeholder or participant'};
const chapters=Object.values(import.meta.glob('../chapters/*.json',{eager:true,import:'default'}));
const hardChapters=Object.values(import.meta.glob('../paths/hard-parts/chapters/*.json',{eager:true,import:'default'}));
const sceneLibrary={...Object.fromEntries(hardChapters.map(ch=>[`hard-parts-${String(ch.number).padStart(2,'0')}`,chapterScene(ch)])),...baseLibrary,...Object.fromEntries(chapters.map(ch=>[`chapter-${String(ch.number).padStart(2,'0')}`,chapterScene(ch)]))};
const studio = document.querySelector('#studio');
studio.innerHTML=`<main class="shell studio"><a class="studio-back" href="/">← Back to the chapter</a><div class="eyebrow">Fieldnotes / Illustration system</div><h1>Small pieces.<br><em>Whole new worlds.</em></h1><p class="studio-intro">The hero’s visual language, ready to reuse. Choose a scene, try a palette, then copy its recipe or download a standalone SVG.</p><div class="studio-workspace"><section class="studio-preview"><div class="studio-controls"><label>Scene<select id="scene-choice">${Object.keys(sceneLibrary).map(name=>`<option value="${name}">${name}</option>`).join('')}</select></label><label>Palette<select id="palette-choice"><option value="original">Original</option>${Object.keys(palettes).map(name=>`<option value="${name}">${name}</option>`).join('')}</select></label><button id="studio-motion" type="button" aria-pressed="false">Pause motion</button></div><div id="scene-preview"></div><div class="studio-actions"><button class="primary" id="export-svg" type="button">Download SVG ↓</button><button class="download" id="copy-recipe" type="button">Copy scene recipe</button></div><p id="studio-status" role="status"></p></section><section class="studio-recipe"><div class="mini-label">Scene recipe · plain JavaScript data</div><pre id="recipe" tabindex="0"></pre></section></div><section class="primitive-library" id="vocabulary"><h2>Choose a shape by its role.</h2><p>A storefront is an experience; a service performs work. Their silhouettes should tell that story before you read the labels.</p><div class="primitive-grid">${Object.entries(vocabulary).map(([kind,description])=>`<article>${renderScene({title:description,platform:false,nodes:[{id:kind,kind,label:kind.toUpperCase(),x:240,y:160,tone:'lilac'}]}).replace('viewBox="0 0 480 375"','viewBox="160 85 160 180"')}<strong>${kind}</strong><p>${description}</p><code>kind: '${kind}'</code></article>`).join('')}</div></section><section class="studio-library"><h2>A shared visual vocabulary.</h2><p>24 primitives, four palettes, one responsive canvas. Shapes express roles; colors provide emphasis. Every scene below uses the same renderer.</p><div class="studio-grid">${Object.entries(sceneLibrary).map(([name,scene])=>`<button type="button" data-preview="${name}" aria-label="Preview ${name}">${renderFigure(scene,{label:name,theme:['operations','principles','checkpoint'].includes(name)?'lilac':'sage'})}</button>`).join('')}</div></section></main>`;
let current;
function update(){const name=document.querySelector('#scene-choice').value,tone=document.querySelector('#palette-choice').value;current=structuredClone(sceneLibrary[name]);if(tone!=='original')current.nodes=current.nodes.map(node=>({...node,tone}));document.querySelector('#scene-preview').innerHTML=renderFigure(current,{label:`Scene / ${name}`,theme:tone==='original'?'sage':tone});document.querySelector('#recipe').textContent=JSON.stringify(current,null,2);}
document.querySelectorAll('select').forEach(el=>el.addEventListener('change',update));
document.querySelectorAll('[data-preview]').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#scene-choice').value=button.dataset.preview;update();document.querySelector('.studio-workspace').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});document.querySelector('#scene-choice').focus({preventScroll:true})}));

document.querySelector('#copy-recipe').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(JSON.stringify(current,null,2));document.querySelector('#studio-status').textContent='Scene recipe copied.'}catch{document.querySelector('#studio-status').textContent='Select and copy the recipe from the code panel.'}});
document.querySelector('#export-svg').addEventListener('click',async()=>{
  // Portable, deliberately static export: no host page CSS or fonts required.
  const styles='<style>.iso-label{text-anchor:middle;font:9px sans-serif;stroke:none}.iso-subtitle{text-anchor:middle;font:10px sans-serif;stroke:none}.iso-role-caption{text-anchor:middle;font:8px sans-serif;stroke:none}.iso-work-ring,.iso-scan{display:none}.iso-badge text{text-anchor:middle;font:9px sans-serif}.iso-packet{stroke-dasharray:5 95;stroke-dashoffset:35}</style>';
  const svg=renderScene(current).replace(/(<svg[^>]*>)/,`$1${styles}`);
  try{await downloadText(`fieldnotes-${document.querySelector('#scene-choice').value}.svg`,svg,'image/svg+xml');document.querySelector('#studio-status').textContent='Standalone SVG exported. Website scenes remain animated.'}catch{document.querySelector('#studio-status').textContent='Export was not completed. Try again.'}
});update();

import { startSceneMotion } from './motion.js';
startSceneMotion();
