import {renderScene,highlightScene} from '../illustrations/engine.js';
import {renderBot} from '../illustrations/sidekick.js';
import {motionEnabled} from '../illustrations/motion-preference.js';

// A deterministic teaching model, independent of rendering and animation timing.
export function traceRecord({guarded,valid}){
 const trace=[{node:'source',text:valid?'A valid duration record enters: 120 ms.':'A malformed record enters: duration is missing.'}];
 if(guarded)trace.push({node:'tester',text:valid?'The tester accepts the numeric duration.':'The tester detects the missing duration.'});
 if(guarded&&!valid)return [...trace,{node:'reject',text:'The record is quarantined. The metrics store stays clean.',outcome:'rejected'}];
 return [...trace,{node:'transform',text:valid?'The transformer converts 120 ms to 0.12 s.':'Without validation, this simplified transformer produces an invalid metric.'},{node:'store',text:valid?'The consumer stores 0.12 s.':'An invalid metric reaches storage. Add validation before transforming.',outcome:valid?'stored':'polluted'}];
}
export function pipelineRecipe(guarded){
 const node=(id,label,x,y,kind='block',tone='sage')=>({id,label,x,y,kind,tone,width:76});
 const nodes=[node('source','SOURCE',75,95,'source','peach'),node('transform','CONVERT',285,170,'terminal'),node('store','METRICS',390,250,'database','peach')];
 const edges=guarded?[{from:'source',to:'tester'},{from:'tester',to:'transform'},{from:'tester',to:'reject',dashed:true},{from:'transform',to:'store'}]:[{from:'source',to:'transform'},{from:'transform',to:'store'}];
 if(guarded)nodes.push(node('tester','VALIDATE',190,105,'gateway','lilac'),node('reject','QUARANTINE',100,260,'queue','honey'));
 return {title:guarded?'A validation filter routes malformed records to quarantine and valid records to conversion and storage.':'Records flow directly from source to conversion and storage without validation.',nodes,edges};
}
export function mountPipelineLab(host,{state,save,reward,xp,action}){
 const lab=state.activity.pipeline||(state.activity.pipeline={guarded:false,valid:false,evidence:[]});
 lab.evidence=Array.isArray(lab.evidence)?lab.evidence:[];
 let disposed=false,running=false,frame=0,trace=[],index=0,elapsed=0,last=0;
 host.innerHTML=`<section class="lesson-panel pipeline-lab"><div class="eyebrow">Chapter 11 / Decision lab · +20 XP</div><h2>Keep the bad data out.</h2><p class="lab-brief">Build a telemetry pipeline that stores valid durations and quarantines malformed records.</p><div class="lab-workspace"><div class="lab-visual"><div class="lab-diagram"></div><div class="lab-trace" role="status" aria-live="polite"></div><button class="lab-step" type="button" hidden>Advance one stage →</button></div><div class="lab-tools"><fieldset><legend>1. Build your route</legend><label><input type="checkbox" id="lab-guard"> Add validation + quarantine</label><p>Keep conversion focused on one job. A tester decides what may proceed.</p></fieldset><fieldset><legend>2. Choose a test record</legend><label><input type="radio" name="record" value="bad"> Malformed · duration missing</label><label><input type="radio" name="record" value="good"> Valid · duration 120 ms</label></fieldset><div class="lab-evidence"></div><button class="lab-retest" type="button" hidden>Test another record ↻</button><div class="lab-pip">${renderBot({xp})}<p data-pip-hint></p></div><details><summary>Why this design? What does it cost?</summary><p>Validation isolates one responsibility and makes rejection explicit. It adds another stage and a quarantine path to maintain. These filters still share a deployment: this does not provide independent scaling or fault isolation.</p></details></div></div><p class="teaching-note">Teaching simulation: missing values become invalid metrics here. Real transformers may reject or throw instead. No performance measurements are implied.</p></section>`;
 const $=s=>host.querySelector(s);
 function evidence(){ $('.lab-evidence').innerHTML=`<strong>Prove your route works</strong><span>${lab.evidence.includes('rejected')?'✓':'○'} Quarantine a malformed record</span><span>${lab.evidence.includes('stored')?'✓':'○'} Store a valid record through validation</span>`; }
 function draw(){ $('.lab-diagram').innerHTML=renderScene(pipelineRecipe(lab.guarded));$('.lab-diagram svg').dataset.manual='true';$('#lab-guard').checked=lab.guarded;$(`[value="${lab.valid?'good':'bad'}"]`).checked=true;$('.lab-trace').textContent='Your route is ready. Run a record to follow each stage.';$('[data-pip-hint]').textContent='Try the malformed record first. Where will it end up?';evidence();syncAction(); }
 function syncAction(){$('.lab-retest').hidden=running||!lab.evidence.includes('rejected')||!lab.evidence.includes('stored');action({label:running?'Record in flight…':lab.evidence.includes('rejected')&&lab.evidence.includes('stored')?'Continue →':'Run this record →',disabled:running,run:()=>lab.evidence.includes('rejected')&&lab.evidence.includes('stored')?location.hash='chapter/11/quiz':run()});}
 function show(){const step=trace[index];host.querySelectorAll('[data-iso-node]').forEach(n=>n.classList.toggle('iso-processing',n.dataset.isoNode===step.node));highlightScene($('.lab-diagram'),[step.node]);$('.lab-trace').textContent=step.text;$('.lab-diagram svg').dataset.recordStage=step.node;host.querySelectorAll('.iso-edge').forEach(e=>e.classList.toggle('lab-flow',e.dataset.from===step.node&&e.dataset.to===trace[index+1]?.node));if(step.outcome){running=false;$('.lab-step').hidden=true;host.querySelectorAll('input').forEach(e=>e.disabled=false);$('.lab-visual').dataset.outcome=step.outcome;if(lab.guarded&&!lab.evidence.includes(step.outcome))lab.evidence.push(step.outcome);save();evidence();$('[data-pip-hint]').textContent=step.outcome==='polluted'?'That reached storage unchecked. Add validation and try again.':step.outcome==='rejected'?'Good catch! Now check that a valid record still gets through.':'The valid metric arrived. A useful boundary rejects bad data without blocking good data.';if(lab.evidence.includes('rejected')&&lab.evidence.includes('stored'))reward();syncAction();}}
 function tick(now){if(disposed||!running)return;const delta=last?Math.min(now-last,100):0;last=now;if(motionEnabled()&&!document.hidden){elapsed+=delta;if(elapsed>=900){elapsed=0;index++;show();}}$('.lab-step').hidden=motionEnabled()||!running;if(running)frame=requestAnimationFrame(tick);}
 function run(){running=true;trace=traceRecord(lab);index=0;elapsed=0;last=0;delete $('.lab-visual').dataset.outcome;host.querySelectorAll('input').forEach(e=>e.disabled=true);syncAction();show();frame=requestAnimationFrame(tick);}
 $('.lab-retest').onclick=run;
 $('.lab-step').onclick=()=>{if(running){elapsed=0;index++;show()}};
 $('#lab-guard').onchange=e=>{lab.guarded=e.target.checked;save();draw()};host.querySelectorAll('[name="record"]').forEach(e=>e.onchange=()=>{lab.valid=e.value==='good';save();draw()});
 draw();return ()=>{disposed=true;cancelAnimationFrame(frame)};
}
