import {appStorage} from '../storage.js';
import {catalog as fundamentals} from '../chapters/catalog.js';
import hardPartsIndex from '../../docs/hard-parts/source-index.json';
export const paths={
 fundamentals:{id:'fundamentals',title:'Fundamentals of Software Architecture',shortTitle:'Fundamentals',entry:'/fundamentals.html',count:24,totalXP:2400,catalog:fundamentals,notes:'/notes',authors:'Mark Richards & Neal Ford',edition:'2020',tag:'Build your foundations',hook:'Build your architect’s mind.',description:'Learn the vocabulary, explore architecture styles, and practice your first design decisions.',parts:['Foundations','Architecture styles','Techniques & people'],level:'Start here · foundational',sourceNote:'Based on Fundamentals of Software Architecture, Richards & Ford (2020).'},
 'hard-parts':{id:'hard-parts',title:'Software Architecture: The Hard Parts',shortTitle:'The Hard Parts',entry:'/hard-parts.html',count:15,totalXP:1500,catalog:hardPartsIndex.map(({number,title,part})=>({number,title,part})),notes:'/notes/hard-parts',authors:'Neal Ford, Mark Richards, Pramod Sadalage & Zhamak Dehghani',edition:'Supplied early-release text · August 2021',tag:'Go deeper into the trade-offs',hook:'Make the hard calls.',description:'Untangle service boundaries, distributed data, workflows, and the decisions with no easy answer.',parts:['Boundaries & decomposition','Distributed decisions','Contracts & analysis'],level:'Go further · distributed architecture',sourceNote:'Based on the supplied early-release text of Software Architecture: The Hard Parts, Ford, Richards, Sadalage & Dehghani (August 2021). All 15 chapters in this version are included.'}
};
export const pathForPage=()=>location.pathname.endsWith('/hard-parts.html')?paths['hard-parts']:paths.fundamentals;
export function rememberLocation(path,chapter,step){try{const all=JSON.parse(appStorage.getItem('fieldnotes-locations-v1')||'{}');all[path]={chapter,step,at:Date.now()};appStorage.setItem('fieldnotes-locations-v1',JSON.stringify(all))}catch{}}
export function lastLocation(path){try{const value=JSON.parse(appStorage.getItem('fieldnotes-locations-v1')||'{}')[path];const config=paths[path];return value&&Number.isInteger(value.chapter)&&value.chapter>=1&&value.chapter<=config.count&&['map','intro','explore','scenario','quiz','apply','system','foundations','card-challenge','tradeoffs','architect','ecosystem','checkpoint','rationale'].includes(value.step)?value:null}catch{return null}}
export function resumeURL(path){const config=paths[path],last=lastLocation(path);if(!last)return config.entry;if(path==='fundamentals'&&last.chapter===1)return '/chapter-one.html'+(last.step==='map'?'#map':'#lesson/'+last.step);return config.entry+`#chapter/${last.chapter}/${last.step}`}
