import {catalog as fundamentals} from '../chapters/catalog.js';
import index0 from '../../docs/hard-parts/source-index.json' with {type:'json'};
import index1 from '../../docs/staff-engineer/source-index.json' with {type:'json'};
import index2 from '../../docs/responsible-engineering/source-index.json' with {type:'json'};
import index3 from '../../docs/sre/source-index.json' with {type:'json'};
import index4 from '../../docs/observability/source-index.json' with {type:'json'};
import index5 from '../../docs/ai-agents/source-index.json' with {type:'json'};
import greenSoftware from '../../docs/green-software/source-index.json' with {type:'json'};
const indexes={'../../docs/hard-parts/source-index.json':index0,'../../docs/staff-engineer/source-index.json':index1,'../../docs/responsible-engineering/source-index.json':index2,'../../docs/sre/source-index.json':index3,'../../docs/observability/source-index.json':index4,'../../docs/ai-agents/source-index.json':index5};
const definitions=[
 {id:'fundamentals',title:'Fundamentals of Software Architecture',shortTitle:'Fundamentals',entry:'/fundamentals.html',catalog:fundamentals,notes:'/notes',authors:'Mark Richards & Neal Ford',edition:'2020',tag:'Build your foundations',hook:'Build your architect’s mind.',description:'Learn the vocabulary, explore architecture styles, and practice your first design decisions.',level:'Architecture · foundations',category:'Architecture',kinds:['storefront','service','database'],labels:['EXPERIENCE','SERVICE','DATA']},
 {id:'hard-parts',title:'Software Architecture: The Hard Parts',shortTitle:'The Hard Parts',entry:'/hard-parts.html',authors:'Neal Ford, Mark Richards, Pramod Sadalage & Zhamak Dehghani',edition:'August 2021 · supplied early release',tag:'Go deeper into the trade-offs',hook:'Make the hard calls.',description:'Untangle service boundaries, distributed data, workflows, and decisions with no easy answer.',level:'Architecture · advanced',category:'Architecture',kinds:['balance','service','queue'],labels:['TRADE-OFF','BOUNDARIES','COORDINATION']},
 {id:'staff-engineer',title:'The Staff Engineer’s Path',shortTitle:'Staff Engineer',authors:'Tanya Reilly',edition:'2022 · first edition',tag:'Grow your influence',hook:'Help people do their best work.',description:'Build trust, navigate ambiguity, lead technical work, and grow through the people around you.',level:'People · technical leadership',category:'People & responsibility',kinds:['mentor','whiteboard','handoff'],labels:['GROW TOGETHER','SHARED DIRECTION','ENABLE OTHERS']},
 {id:'responsible-engineering',title:'Responsible Software Engineering',shortTitle:'Responsible Engineering',authors:'Daniel J. Barrett',edition:'2025 · first edition',tag:'Consider the people affected',hook:'Build software that deserves trust.',description:'Explore fairness, societal context, privacy, downstream consequences, and environmental impact.',level:'People · responsible practice',category:'People & responsibility',kinds:['stakeholders','shield','leaf'],labels:['PEOPLE','TRUST','IMPACT']},
 {id:'sre',title:'Site Reliability Engineering',shortTitle:'Site Reliability',authors:'Betsy Beyer, Chris Jones, Jennifer Petoff & Niall Richard Murphy (editors)',edition:'2016 · first edition',tag:'Operate with confidence',hook:'Turn reliability into a practice.',description:'Balance risk, reduce toil, respond to incidents, and design systems and teams that recover.',level:'Production · reliability',category:'Production',kinds:['alert','colleague','service'],labels:['NOTICE','RESPOND','RECOVER']},
 {id:'observability',title:'Observability Engineering',shortTitle:'Observability',authors:'Charity Majors, Liz Fong-Jones & George Miranda',edition:'2022 · first edition',tag:'Ask better questions',hook:'Follow the evidence.',description:'Connect rich events, traces, and human curiosity to understand what production is doing.',level:'Production · investigation',category:'Production',kinds:['trace','experiment','listening'],labels:['CONTEXT','INVESTIGATE','SHARE LEARNING']},
 {id:'ai-agents',title:'Building Applications with AI Agents',shortTitle:'AI Agents',authors:'Michael Albada',edition:'2025 · first edition',tag:'Design useful autonomy',hook:'Make agents useful—and accountable.',description:'Combine tools, memory, orchestration, evaluation, and human collaboration into dependable agent systems.',level:'AI · agent systems',category:'AI systems',kinds:['agent','gateway','colleague'],labels:['REASON & ACT','CHECK','COLLABORATE']},
 {id:'green-software',title:'Building Green Software',shortTitle:'Green Software',catalog:greenSoftware,authors:'Anne Currie, Sarah Hsu & Sara Bergman',edition:'March 2024 · first edition',tag:'Build with fewer resources',hook:'Make useful software with a smaller footprint.',description:'Explore energy, carbon-aware operation, hardware longevity, and measurement. Turn the book into a practical improvement plan.',level:'Sustainability · software and operations',category:'Sustainability',kinds:['leaf','deployment','gauge'],labels:['CARBON','RESOURCES','EVIDENCE']},
];
export const paths=Object.fromEntries(definitions.map(def=>{
 const catalog=def.catalog||indexes[`../../docs/${def.id}/source-index.json`]||[];
 const key=def.id==='fundamentals'?'fieldnotes-book-v1':`fieldnotes-${def.id}-v1`;
 return [def.id,{...def,key,catalog,count:catalog.length,totalXP:catalog.length*100,parts:[...new Set(catalog.map(ch=>ch.part))],entry:def.entry||`/learn.html?path=${def.id}`,notes:def.notes||`/notes/${def.id}`,sourceNote:`Based on ${def.title}, ${def.authors} (${def.edition}). Covers the numbered chapters in the supplied text.`}];
}));
export const progressConfigs=Object.fromEntries(Object.values(paths).map(p=>[p.id,{key:p.key,count:p.count,total:p.totalXP}]));
export function pathScene(path){return {title:`${path.title}: ${path.labels.join(', then ')}.`,nodes:path.kinds.map((kind,i)=>({id:`role-${i}`,kind,label:path.labels[i],x:[235,105,365][i],y:[80,225,235][i],tone:['sage','lilac','peach'][i]})),edges:[{from:'role-0',to:'role-1'},{from:'role-1',to:'role-2'}],sequence:path.labels.map((text,i)=>({node:`role-${i}`,text}))}}
