import {progressConfigs} from './paths/registry.js';
const ledgers=Object.fromEntries(Object.values(progressConfigs).map(p=>[p.key,p]));
import {appStorage,storageKeys,storageSnapshot,flushStorage,native} from './storage.js';
import {downloadText} from './downloads.js';
const object=value=>value&&typeof value==='object'&&!Array.isArray(value);
function safe(value){if(value&&typeof value==='object')for(const [key,child] of Object.entries(value)){if(['__proto__','constructor','prototype'].includes(key))throw new Error('Unsupported backup field');safe(child)}}
export function parseBackup(text){if(text.length>2000000)throw new Error('Backup is too large');const parsed=JSON.parse(text);safe(parsed);if(parsed.format!=='fieldnotes-backup'||parsed.version!==1||!object(parsed.entries))throw new Error('Choose a Fieldnotes progress backup');const result={};for(const [key,value] of Object.entries(parsed.entries)){if(!storageKeys.includes(key)||typeof value!=='string')throw new Error('Unsupported backup entry');if(key==='fieldnotes-motion-v1'){if(!['on','off','system'].includes(value))throw new Error('Invalid motion setting')}else{const data=JSON.parse(value);safe(data);if(!object(data))throw new Error('Invalid progress record');if(!!ledgers[key]){if(data.version!==1||!object(data.chapters))throw new Error('Invalid chapter ledger');const max=ledgers[key].count;for(const [id,ch] of Object.entries(data.chapters)){if(!/^\d+$/.test(id)||+id<1||+id>max||!object(ch))throw new Error('Invalid chapter');if(ch.missions&&!object(ch.missions)||ch.activity&&!object(ch.activity)||ch.read&&!Array.isArray(ch.read))throw new Error('Invalid chapter data')}}}result[key]=value}return result}
export function mergeLedger(current,incoming){const out=structuredClone(current);for(const [id,ch] of Object.entries(incoming.chapters)){if(!out.chapters[id]){out.chapters[id]=ch;continue}const old=out.chapters[id];old.missions={...ch.missions,...old.missions};for(const [mission,earned] of Object.entries(ch.missions||{}))if(earned===true)old.missions[mission]=true;old.read=[...new Set([...(old.read||[]),...(ch.read||[])])];const activity={...ch.activity,...old.activity};for(const key of ['seen','compared'])if(ch.activity?.[key]||old.activity?.[key])activity[key]=[...new Set([...(old.activity?.[key]||[]),...(ch.activity?.[key]||[])])];for(const key of ['draft','answers'])if(Array.isArray(ch.activity?.[key]))activity[key]=Array.from({length:Math.max(ch.activity[key].length,old.activity?.[key]?.length||0)},(_,i)=>old.activity?.[key]?.[i]??ch.activity[key][i]);old.activity=activity}return out}
export function mountBackup(host){host.insertAdjacentHTML('beforeend',`<section class="backup-panel"><div><strong>Keep your learning with you.</strong><p>Export a backup to move between browser and Android. Import merges earned progress; existing writing stays yours.</p></div><div class="backup-actions"><button id="export-progress" type="button">Export progress ↓</button><label class="import-progress">Import progress ↑<input id="import-progress" type="file" accept="application/json,.json"></label></div><p id="backup-status" role="status"></p></section>`);const status=host.querySelector('#backup-status');host.querySelector('#export-progress').onclick=async()=>{try{await downloadText('fieldnotes-progress.json',JSON.stringify({format:'fieldnotes-backup',version:1,createdAt:new Date().toISOString(),entries:storageSnapshot()},null,2),'application/json');status.textContent=native?'Backup ready to save or share.':'Backup downloaded.'}catch{status.textContent='Export was not completed. Your progress is still here.'}};host.querySelector('#import-progress').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;const incoming=parseBackup(await file.text());const merged={};for(const [key,value] of Object.entries(incoming)){const current=appStorage.getItem(key);if(current&&(!!ledgers[key]))merged[key]=JSON.stringify(mergeLedger(JSON.parse(current),JSON.parse(value)));else if(!current)merged[key]=value}for(const [key,value] of Object.entries(merged))appStorage.setItem(key,value);await flushStorage();location.reload()}catch(error){status.textContent=error.message||'This backup could not be imported.';event.target.value=''}}}
