import {renderCourseBot,courseEvolutionFor,nextCourseEvolution,courseEvolutions} from './illustrations/course-sidekicks.js';
import {navigationIcon} from './navigation-icons.js';
import {downloadText} from './downloads.js';
import {mountPipelineLab} from './activities/pipeline.js';
import { chapterScene as sceneFor } from './chapters/visuals.js';
import './style.css';
import './illustrations/illustrations.css';
import './course.css';
import './book.css';
import {pathForPage,rememberLocation,lastLocation,resumeURL} from './paths/catalog.js';
const path=pathForPage();
if(!path)throw new Error('Unknown learning path');
document.title=path.title+' — Fieldnotes';
const hard=path.id!=='fundamentals',catalog=path.catalog,TOTAL_XP=path.totalXP;
const guided=ch=>hard||ch?.number===11;
const sourceRef=ch=>ch.source.reference||`printed pp. ${ch.source.pages}`;
import {progressFor,companionXP} from './progress.js';
const {chapterState,chapterXP,totalXP,awardMission,completeReading,saveProgress,storageAvailable}=progressFor(path.id);
import { renderBot, evolutionFor, nextEvolution, evolutions } from './illustrations/sidekick.js';
import { renderScene } from './illustrations/engine.js';
import { bookshop } from './illustrations/scenes.js';
import { startSceneMotion, wireScenePlayer, setSceneStep } from './illustrations/motion.js';
const fundamentalsContent=import.meta.glob('./chapters/*.json',{eager:true,import:'default'});
const pathContent=import.meta.glob('./paths/*/chapters/*.json',{import:'default'});
const modules=hard?await Promise.all(Object.entries(pathContent).filter(([file])=>file.startsWith(`./paths/${path.id}/chapters/`)).map(([,load])=>load())):fundamentalsContent;
const content=new Map(Object.values(modules).map(ch=>[ch.number,ch]));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
const lessons=[{id:'intro',title:'See the idea',icon:'◇'},{id:'explore',title:'Explore the concepts',icon:'▧',xp:20},{id:'scenario',title:'Make a decision',icon:'⇌',xp:20},{id:'quiz',title:'Check your thinking',icon:'✦',xp:20},{id:'apply',title:'Make it yours',icon:'▱',xp:40}];
let currentChapter=null,currentStep='map',routeToken=0;
let toastTimer, activityAction=null, disposeActivity=null;
function setActivityAction(value){activityAction=value;syncActivityAction()}
function syncActivityAction(){if(activityAction){$('#book-next').textContent=activityAction.label;$('#book-next').disabled=!!activityAction.disabled}}
document.body.classList.add('course-mode','book-mode');document.body.classList.toggle('hard-parts-path',hard);
$('#app').innerHTML=`<header><nav class="nav shell" aria-label="Main navigation"><a class="brand" href="/"><span class="book-logo">◇</span> fieldnotes<span style="color:var(--orange)">.</span></a><div class="course-header-tools"><a class="book-nav-button path-home" href="/" aria-label="Learning paths" title="Learning paths">${navigationIcon('paths')} <span>Paths</span></a><button id="library-button" class="book-nav-button" type="button" aria-label="All chapters" title="All chapters">${navigationIcon('chapters')} <span>All chapters</span></button><button id="chapter-map-button" class="book-nav-button" type="button" aria-label="Chapter map" title="Chapter map" hidden>${navigationIcon('map')} <span>Chapter map</span></button><div class="book-avatar"></div><div class="book-xp"><strong></strong><small></small></div><button class="motion-toggle" type="button" aria-label="Pause animations" aria-pressed="false">Ⅱ</button></div></nav></header><nav class="course-progress" aria-label="Jump to a lesson" hidden><div class="shell"><div class="course-progress-label"><span id="book-location"></span><span id="book-chapter-score"></span></div><div class="course-steps">${lessons.map((l,i)=>`<button data-go="${l.id}" type="button" aria-label="Jump to ${l.title}"><span>${i+1}</span><i></i><small class="step-name">${l.title}</small></button>`).join('')}</div></div></nav><main class="course-main shell"><div class="course-stage" id="book-stage"></div></main>`;
const footer=document.createElement('nav');footer.className='course-bottom';footer.setAttribute('aria-label','Lesson navigation');footer.hidden=true;footer.innerHTML='<div class="shell"><button id="book-back" type="button">← Back</button><span id="book-position"></span><button id="book-skip" type="button" hidden>Skip</button><button class="primary" id="book-next" type="button">Continue →</button></div>';document.body.append(footer);
const toast=document.createElement('div');toast.className='quest-toast';toast.setAttribute('role','status');document.body.append(toast);
function announce(text){toast.textContent=text;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3600)}
function reward(mission){const amount=awardMission(currentChapter.number,mission);if(amount){announce(`+${amount} XP · ${evolutionFor(companionXP()).name} is growing with you.`);$('.book-avatar').classList.remove('pip-evolve');void $('.book-avatar').offsetWidth;$('.book-avatar').classList.add('pip-evolve')}updateChrome()}
function updateChrome(){const xp=totalXP(),next=nextEvolution(companionXP());$('.book-avatar').innerHTML=renderBot({xp:companionXP(),decorative:false});$('.book-avatar').title=evolutionFor(companionXP()).name;$('.book-xp strong').textContent=`${xp.toLocaleString()} / ${TOTAL_XP.toLocaleString()} XP`;$('.book-xp small').textContent=next?`Next form: ${next.xp.toLocaleString()} XP`:'Final form unlocked';if(currentChapter){$('#book-chapter-score').textContent=`${chapterXP(currentChapter.number)} / 100 chapter XP`;const state=chapterState(currentChapter.number);document.querySelectorAll('[data-go]').forEach(b=>{b.classList.toggle('complete',!!state.missions[b.dataset.go]||state.read.includes(b.dataset.go));b.toggleAttribute('aria-current',b.dataset.go===currentStep);if(b.dataset.go===currentStep)b.setAttribute('aria-current','step')});const index=lessons.findIndex(l=>l.id===currentStep);if(index>=0){$('#book-position').textContent=`${index+1} / ${lessons.length}`;$('#book-next').textContent=currentStep==='intro'?'Got it, continue →':currentStep==='apply'?'Chapter map ↗':state.missions[currentStep]?'Continue →':'Skip for now →'}}}
window.addEventListener('book:progress',()=>{updateChrome();syncActivityAction()});
function go(number,step='map'){location.hash=number===null?'library':`chapter/${number}/${step}`}
$('#library-button').addEventListener('click',()=>go(null));$('#chapter-map-button').addEventListener('click',()=>go(currentChapter.number));
document.querySelectorAll('.course-steps [data-go]').forEach(b=>b.addEventListener('click',()=>go(currentChapter.number,b.dataset.go)));
$('#book-back').addEventListener('click',()=>{const i=lessons.findIndex(l=>l.id===currentStep);go(currentChapter.number,i<=0?'map':lessons[i-1].id)});
$('#book-skip').onclick=()=>{const i=lessons.findIndex(l=>l.id===currentStep);go(currentChapter.number,i===lessons.length-1?'map':lessons[i+1].id)};
$('#book-next').addEventListener('click',()=>{if(activityAction){activityAction.run();return}if(currentStep==='intro')completeReading(currentChapter.number,'intro');const i=lessons.findIndex(l=>l.id===currentStep);go(currentChapter.number,i===lessons.length-1?'map':lessons[i+1].id)});

function player(ch,compact=false){const scene=sceneFor(ch);return `<div class="chapter-scene ${compact?'compact':''}" data-scene-player data-playing="true"><div class="iso-kicker"><span>IN MOTION / ${esc(ch.title)}</span><span>↗</span></div>${renderScene(scene)}<div class="scene-caption" data-scene-caption>${esc(ch.visual.steps[0].text)}</div><div class="scene-controls"><div class="scene-step-buttons">${ch.visual.steps.map((s,i)=>`<button data-scene-step="${i}" type="button" aria-pressed="${i===0}" aria-label="Step ${i+1}: ${esc(s.text)}">${i+1}</button>`).join('')}</div><button type="button" data-scene-play aria-pressed="true">Ⅱ Pause sequence</button></div><p class="scene-note">Illustrated teaching model · tap a step to examine it.</p></div>`}
function attachPlayers(){document.querySelectorAll('[data-scene-player]').forEach(wireScenePlayer)}
function library(){currentChapter=null;currentStep='library';const xp=totalXP(),pipXP=companionXP();const completed=catalog.filter(c=>chapterXP(c.number)===100).length;const next=catalog.find(c=>chapterXP(c.number)<100)||catalog[0];$('#book-stage').innerHTML=`<section class="book-library"><div class="library-hero"><div><div class="eyebrow">${esc(path.shortTitle)} / ${path.count} chapters</div><h1>${esc(path.hook)}</h1><p>${esc(path.description)}</p><button id="continue-book" class="primary">${lastLocation(path.id)?'Resume your journey':'Start the journey'} <span>→</span></button><div class="library-stats"><span><b>${completed}</b> / ${path.count} chapters completed</span><span><b>${xp}</b> XP earned</span><span>${storageAvailable()?'Progress saved on this device':'Progress lasts for this visit'}</span></div></div><div class="library-pip"><div class="library-pip-bot">${renderCourseBot({course:path.id,xp,decorative:false})}</div><span class="pip-orbit"></span><span class="pip-orbit second"></span><div class="library-pip-caption"><strong>${courseEvolutionFor(path.id,xp).name}</strong><p>${nextCourseEvolution(path.id,xp)?`The next course form unlocks at ${nextCourseEvolution(path.id,xp).xp} XP in this book. Your overall Pip grows alongside it.`:'All ten course forms earned. Your overall Pip keeps growing across the library.'}</p><a class="pip-collection-link" href="/companions.html?track=${path.id}">See this course’s ten forms →</a></div><div class="evolution-track">${courseEvolutions(path.id).map(e=>`<span class="${xp>=e.xp?'unlocked':''}" title="${e.name}">${e.xp===0?'✦':e.xp}<i></i></span>`).join('')}</div></div></div><div class="library-toolbar"><div><h2>Your learning atlas.</h2><p>Every chapter is open. Pick a starting point.</p></div><label class="chapter-search">⌕ <input id="chapter-search" type="search" placeholder="Find a chapter…" aria-label="Find a chapter"/></label></div><div id="chapter-groups">${path.parts.map((part,p)=>`<section class="chapter-group" data-part="${part}"><div class="chapter-group-label"><span>0${p+1}</span><h3>${part}</h3></div><div class="chapter-cards">${catalog.filter(c=>c.part===part).map(c=>`<button class="chapter-card" data-open-chapter="${c.number}" aria-label="Open chapter ${c.number}: ${esc(c.title)}"><span class="chapter-number">${String(c.number).padStart(2,'0')}</span><span class="chapter-card-body"><strong>${esc(c.title)}</strong><small>${chapterXP(c.number)===100?'✓ Missions complete':!hard&&c.number===1?'8 discoveries · 100 XP':'5 discoveries · 100 XP'}</small><span class="chapter-card-bar"><i style="width:${chapterXP(c.number)}%"></i></span></span><span class="chapter-arrow">↗</span></button>`).join('')}</div></section>`).join('')}</div><p id="no-chapters" hidden>No chapters match that search.</p><p class="library-source">${esc(path.sourceNote)} Independent learning companion. Summaries paraphrase the book; interactive scenarios are teaching extensions.</p></section>`;
 $('#continue-book').addEventListener('click',()=>lastLocation(path.id)?location.href=resumeURL(path.id):openChapter(next.number));document.querySelectorAll('[data-open-chapter]').forEach(b=>b.addEventListener('click',()=>openChapter(+b.dataset.openChapter)));$('#chapter-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();let found=0;document.querySelectorAll('[data-open-chapter]').forEach(b=>{b.hidden=!b.textContent.toLowerCase().includes(q);if(!b.hidden)found++});document.querySelectorAll('.chapter-group').forEach(g=>g.hidden=![...g.querySelectorAll('.chapter-card')].some(b=>!b.hidden));$('#no-chapters').hidden=found>0})}
function openChapter(n){if(!hard&&n===1){location.href='/chapter-one.html#map';return}go(n)}
function chapterMap(ch){const state=chapterState(ch.number),xp=chapterXP(ch.number);$('#book-stage').innerHTML=`<section class="course-map chapter-overview"><div class="map-intro"><div class="eyebrow"><span class="pill">Chapter ${String(ch.number).padStart(2,'0')}</span>${esc(ch.part)}</div><h1>${esc(ch.title)}</h1><p>${esc(ch.subtitle)}</p>${player(ch,true)}<a class="chapter-notes" href="${path.notes}/chapter-${String(ch.number).padStart(2,'0')}.md" target="_blank" rel="noopener">Read chapter notes ↗</a><p class="map-source">Source: ${esc(sourceRef(ch))} · ${esc(path.authors)}</p></div><div class="map-journey"><div class="pip-status"><div class="map-pip">${renderBot({xp:companionXP()})}</div><div><b>${xp===100?'All missions complete!':'A new chapter, a new perspective.'}</b><p>${xp} / 100 XP in this chapter. Your companion grows across the whole book.</p></div></div><div class="map-path">${lessons.map((l,i)=>`<button class="map-stop ${state.missions[l.id]||state.read.includes(l.id)?'complete':''}" data-start-lesson="${l.id}" aria-label="Open ${l.title}"><span class="stop-orb"><span class="stop-icon">${l.icon}</span><span class="stop-number">${i+1}</span></span><span class="stop-copy"><strong>${l.title}</strong><small>${l.xp?`+${l.xp} XP`:'Meet the core idea'}</small></span><span class="stop-check">${state.missions[l.id]||state.read.includes(l.id)?'✓':'↗'}</span></button>`).join('')}</div><div class="chapter-map-links"><button id="previous-chapter">← Previous chapter</button><button id="next-chapter">${ch.number===path.count?'All chapters ↗':'Next chapter →'}</button></div></div></section>`;document.querySelectorAll('[data-start-lesson]').forEach(b=>b.addEventListener('click',()=>go(ch.number,b.dataset.startLesson)));$('#previous-chapter').addEventListener('click',()=>ch.number===1?go(null):openChapter(ch.number-1));$('#next-chapter').addEventListener('click',()=>ch.number===path.count?go(null):openChapter(ch.number+1));attachPlayers()}
function heading(ch,kicker,title,subtitle=''){return `<div class="section-heading"><div><div class="eyebrow">Chapter ${ch.number} / ${esc(kicker)}</div><h2>${esc(title)}</h2></div>${subtitle?`<p class="section-sub">${esc(subtitle)}</p>`:''}</div>`}
function renderIntro(ch){$('#book-stage').innerHTML=`<section class="lesson-panel book-intro">${heading(ch,'The big idea',ch.subtitle)}<div class="book-split"><div class="chapter-prose"><h3>${esc(ch.title)}</h3><p>${esc(ch.summary)}</p><div class="chapter-promise"><b>What you’ll take away</b><ul>${ch.concepts.map(c=>`<li>${esc(c.title)}</li>`).join('')}</ul></div><p class="teaching-note">Source: ${esc(sourceRef(ch))}. Exercises and animated scenarios are original teaching extensions.</p></div>${player(ch)}</div></section>`;attachPlayers()}
function renderExplore(ch){const state=chapterState(ch.number);state.activity.seen=Array.isArray(state.activity.seen)?state.activity.seen:[];let selected=Number(state.activity.concept||0);if(selected>=ch.concepts.length)selected=0;$('#book-stage').innerHTML=`<section class="lesson-panel">${heading(ch,'Explore / +20 XP','Take the idea apart.','Visit every concept. Look for the distinctions that change a decision.')}<div class="book-concepts-nav" role="tablist" aria-label="Chapter concepts">${ch.concepts.map((c,i)=>`<button role="tab" data-concept="${i}" id="concept-${i}" aria-controls="chapter-concept" aria-selected="false">${i+1}. ${esc(c.title)}</button>`).join('')}</div><div class="book-split"><div id="chapter-concept" role="tabpanel" tabindex="0"></div>${player(ch)}</div><div class="misconceptions"><h3>Two traps to watch for.</h3>${ch.misconceptions.map(m=>`<details><summary>${esc(m.claim)}</summary><p>${esc(m.correction)}</p></details>`).join('')}</div></section>`;
 function select(i,focus=false){selected=i;state.activity.concept=i;if(!state.activity.seen.includes(i))state.activity.seen.push(i);const c=ch.concepts[i];$('#chapter-concept').setAttribute('aria-labelledby',`concept-${i}`);$('#chapter-concept').innerHTML=`<div class="concept-page content-swap"><span class="concept-page-number">${String(i+1).padStart(2,'0')} / ${ch.concepts.length}</span><h3>${esc(c.title)}</h3><p>${esc(c.body)}</p><div class="example"><b>Teaching example</b>${esc(c.example)}</div><p class="concept-source">Source: ${esc(c.source)}</p><div class="concept-arrows"><button id="concept-prev" ${i===0?'disabled':''}>← Previous</button><span>${state.activity.seen.length} / ${ch.concepts.length} explored</span><button id="concept-next" ${i===ch.concepts.length-1?'disabled':''}>Next idea →</button></div></div>`;document.querySelectorAll('[data-concept]').forEach((b,j)=>{b.classList.toggle('active',j===i);b.setAttribute('aria-selected',String(j===i));b.tabIndex=j===i?0:-1;if(focus&&j===i)b.focus()});$('#concept-prev').onclick=()=>select(i-1);$('#concept-next').onclick=()=>select(i+1);saveProgress();if(state.activity.seen.length===ch.concepts.length)reward('explore');if(guided(ch))setActivityAction({label:i<ch.concepts.length-1?'Next concept →':hard?'Try the decision lab →':'Build a pipeline →',run:()=>i<ch.concepts.length-1?select(i+1):go(ch.number,'scenario')})}
 document.querySelectorAll('[data-concept]').forEach((b,i)=>{b.onclick=()=>select(i);b.onkeydown=e=>{let n;if(e.key==='ArrowRight')n=(i+1)%ch.concepts.length;if(e.key==='ArrowLeft')n=(i-1+ch.concepts.length)%ch.concepts.length;if(n!==undefined){e.preventDefault();select(n,true)}}});select(selected);attachPlayers()}
function renderScenario(ch){if(!hard&&ch.number===11){disposeActivity=mountPipelineLab($('#book-stage'),{state:chapterState(11),save:saveProgress,reward:()=>reward('scenario'),xp:totalXP(),action:setActivityAction});return}const state=chapterState(ch.number);state.activity.compared=Array.isArray(state.activity.compared)?state.activity.compared:[];const sc=ch.scenario;$('#book-stage').innerHTML=`<section class="lesson-panel">${heading(ch,'Decision lab / +20 XP',sc.title,'Try both approaches. There is a cost on each side.')}<div class="book-split"><div><p class="scenario-context">${esc(sc.context)}</p><div class="scenario-options">${sc.options.map((o,i)=>`<button data-choice="${i}" aria-pressed="false"><span>${i===0?'A':'B'}</span>${esc(o.label)}</button>`).join('')}</div><div id="decision-consequence" aria-live="polite"><p class="empty-consequence">Choose an approach to reveal what you gain and what you accept.</p></div></div>${player(ch)}</div><p class="teaching-note">Teaching extension. These are contextual consequences, not measured performance claims or universal ratings.</p></section>`;
 document.querySelectorAll('[data-choice]').forEach((b,i)=>b.onclick=()=>{if(!state.activity.compared.includes(i))state.activity.compared.push(i);state.activity.choice=i;const o=sc.options[i];$('#decision-consequence').innerHTML=`<div class="outcome content-swap"><div class="outcome-benefit"><b>What you gain</b><p>${esc(o.benefit)}</p></div><div class="outcome-cost"><b>What you accept</b><p>${esc(o.cost)}</p></div><p>${esc(o.consequence)}</p>${state.activity.compared.length===2?`<div class="scenario-debrief">${esc(sc.debrief)}</div>`:'<small>Now try the other approach to compare the trade-off.</small>'}</div>`;document.querySelectorAll('[data-choice]').forEach((x,j)=>{x.classList.toggle('active',i===j);x.setAttribute('aria-pressed',String(i===j))});const svg=$('[data-scene-player] svg');setSceneStep(svg,i%ch.visual.steps.length);saveProgress();if(state.activity.compared.length===2)reward('scenario');if(hard)setActivityAction({label:state.activity.compared.length===2?'Continue →':'Compare both approaches',disabled:state.activity.compared.length<2,run:()=>go(ch.number,'quiz')})});attachPlayers();if(hard)setActivityAction({label:'Choose an approach',disabled:true,run:()=>{}});if(Number.isInteger(state.activity.choice)&&state.activity.choice<sc.options.length)$(`[data-choice="${state.activity.choice}"]`).click()}
function renderQuiz(ch){const state=chapterState(ch.number);state.activity.answers=Array.isArray(state.activity.answers)?state.activity.answers:[];let index=Math.min(Number(state.activity.quizIndex||0),ch.quiz.length),pendingAnswer;function draw(){if(index===ch.quiz.length){const score=ch.quiz.filter((q,i)=>state.activity.answers[i]===q.answer).length;$('#book-stage').innerHTML=`<section class="lesson-panel quiz-finish"><div class="quiz-finish-pip">${renderBot({xp:companionXP()})}</div><div class="eyebrow">Reflection complete</div><h2>${score} of ${ch.quiz.length} on this attempt.</h2><p>Understanding grows through feedback. Take this chapter’s ideas into a decision of your own.</p><button class="primary" id="quiz-retry">Practice again ↻</button></section>`;reward('quiz');if(guided(ch))setActivityAction({label:'Apply what you learned →',run:()=>go(ch.number,'apply')});$('#quiz-retry').onclick=()=>{state.activity.answers=[];index=0;state.activity.quizIndex=0;saveProgress();draw()};return}
 const q=ch.quiz[index],answer=state.activity.answers[index];$('#book-stage').innerHTML=`<section class="lesson-panel book-quiz">${heading(ch,'Reflection / +20 XP','What would you do?')}<div class="book-split"><div class="quiz-card"><div class="mini-label">Question ${index+1} / ${ch.quiz.length}</div><h3 class="quiz-question">${esc(q.question)}</h3><div class="quiz-options">${q.options.map((o,i)=>`<button class="quiz-option ${answer!==undefined?(i===q.answer?'correct':i===answer?'incorrect':''):''}" data-answer="${i}" ${answer!==undefined?'aria-disabled="true"':''}><span class="option-letter">${'ABC'[i]}</span>${esc(o)}</button>`).join('')}</div><p class="quiz-feedback" aria-live="polite">${answer!==undefined?esc((answer===q.answer?'Exactly. ':'Not quite. ')+q.explanation):''}</p><button class="quiz-next" id="next-reflection" ${answer===undefined?'hidden':''}>${index===ch.quiz.length-1?'See your takeaway →':'Next question →'}</button></div><div>${player(ch,true)}<div class="quiz-pip-tip">${renderBot({xp:companionXP()})}<p>No timer. No lost lives.<br>Read the reasoning, then keep going.</p></div></div></div></section>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(state.activity.answers[index]!==undefined)return;if(guided(ch)){pendingAnswer=+b.dataset.answer;document.querySelectorAll('[data-answer]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});setActivityAction({label:'Check answer',run:()=>{state.activity.answers[index]=pendingAnswer;pendingAnswer=undefined;saveProgress();draw()}});return}state.activity.answers[index]=+b.dataset.answer;saveProgress();draw()});$('#next-reflection').onclick=()=>{index++;state.activity.quizIndex=index;saveProgress();draw()};attachPlayers();if(guided(ch))setActivityAction(answer===undefined?{label:'Select an answer',disabled:true,run:()=>{}}:{label:index===ch.quiz.length-1?'See your takeaway →':'Next question →',run:()=>$('#next-reflection').click()})};draw()}
function renderApply(ch){const state=chapterState(ch.number);state.activity.draft=Array.isArray(state.activity.draft)?state.activity.draft:[];$('#book-stage').innerHTML=`<section class="lesson-panel">${heading(ch,'Put it into practice / +40 XP',ch.exercise.title)}<div class="book-split"><div class="chapter-prose"><p>${esc(ch.exercise.prompt)}</p>${player(ch,true)}<p class="teaching-note">Your writing stays on this device when browser storage is available. This exercise is a teaching extension.</p></div><form class="chapter-workbook">${ch.exercise.fields.map((f,i)=>`<label for="work-${i}">${esc(f.label)}</label><textarea id="work-${i}" data-work="${i}" required minlength="12" maxlength="3000" placeholder="${esc(f.placeholder)}">${esc(state.activity.draft[i]||'')}</textarea>`).join('')}<p class="workbook-hint">Write at least a short sentence in each field. Be specific about your context.</p><button class="primary" type="submit">Save & download my reflection ↓</button><p id="work-status" role="status"></p></form></div></section>`;document.querySelectorAll('[data-work]').forEach(input=>input.oninput=()=>{state.activity.draft[+input.dataset.work]=input.value;saveProgress();$('#work-status').textContent=storageAvailable()?'Draft saved on this device.':'Browser saving unavailable; download to keep this draft.'});$('.chapter-workbook').onsubmit=async e=>{e.preventDefault();const values=[...document.querySelectorAll('[data-work]')].map(x=>x.value.trim());if(values.some(v=>v.length<12)){ $('#work-status').textContent='Add a specific sentence in every field before completing.';return}const text=`# ${path.title}\n\nChapter ${ch.number}: ${ch.title}\n\n${ch.exercise.title}\n\n`+ch.exercise.fields.map((f,i)=>`## ${f.label}\n${values[i]}\n`).join('\n');try{await downloadText(`${hard?path.id+'-':''}chapter-${String(ch.number).padStart(2,'0')}-reflection.md`,text)}catch{$('#work-status').textContent='Export was not completed. Your draft is kept here.';return}reward('apply');$('#work-status').textContent='Reflection downloaded. Mission complete.';if(guided(ch))setActivityAction({label:'Chapter map →',run:()=>go(ch.number,'map')})};attachPlayers()}
function renderRoute(){disposeActivity?.();disposeActivity=null;activityAction=null;$('#book-next').disabled=false;document.body.classList.toggle('guided-chapter',hard||/^#chapter\/11\//.test(location.hash));$('#book-skip').hidden=!(hard||/^#chapter\/11\//.test(location.hash));if(!hard&&(location.hash==='#map'||location.hash.startsWith('#lesson/'))){location.replace('/chapter-one.html'+location.hash);return}routeToken++;const match=location.hash.match(/^#chapter\/(\d+)(?:\/(\w+))?$/);$('.course-stage').scrollTop=0;if(!match){library();$('.course-progress').hidden=true;$('#chapter-map-button').hidden=true;footer.hidden=true}else{const n=+match[1];if(!hard&&n===1){location.replace('/chapter-one.html#map');return}const ch=content.get(n);if(!ch){$('#book-stage').innerHTML='<section class="chapter-prose"><h2>Chapter not found</h2><p>Choose a chapter from the library.</p><a href="#library">Return to all chapters →</a></section>';currentChapter=null;$('.course-progress').hidden=true;footer.hidden=true;$('#chapter-map-button').hidden=true;return}currentChapter=ch;currentStep=['map',...lessons.map(l=>l.id)].includes(match[2])?match[2]:'map';rememberLocation(path.id,n,currentStep);$('.course-progress').hidden=false;$('#chapter-map-button').hidden=false;footer.hidden=currentStep==='map';$('#book-location').textContent=`${String(n).padStart(2,'0')} / ${ch.title} · ${currentStep==='map'?'Chapter map':lessons.find(l=>l.id===currentStep).title}`;({map:chapterMap,intro:renderIntro,explore:renderExplore,scenario:renderScenario,quiz:renderQuiz,apply:renderApply}[currentStep])(ch)}updateChrome();if(currentChapter&&guided(currentChapter)&&currentStep==='apply')setActivityAction({label:chapterState(currentChapter.number).missions.apply?'Chapter map →':'Save & download reflection',run:()=>chapterState(currentChapter.number).missions.apply?go(currentChapter.number,'map'):$('.chapter-workbook').requestSubmit()});syncActivityAction();const heading=$('#book-stage h1,#book-stage h2');if(heading){heading.tabIndex=-1;heading.focus({preventScroll:true})}$('#book-stage').classList.remove('lesson-enter');void $('#book-stage').offsetWidth;$('#book-stage').classList.add('lesson-enter')}
window.addEventListener('hashchange',renderRoute);startSceneMotion();renderRoute();
