import {mountBackup} from './backup.js';
import './style.css';
import './course.css';
import './illustrations/illustrations.css';
import './home.css';
import {paths,lastLocation,resumeURL} from './paths/catalog.js';
import {progressFor,companionXP} from './progress.js';
import {renderBot,evolutionFor,nextEvolution} from './illustrations/sidekick.js';
import {renderScene} from './illustrations/engine.js';
import {startSceneMotion} from './illustrations/motion.js';
const legacy=()=>{if(location.hash==='#library'||location.hash.startsWith('#chapter/')){location.replace('/fundamentals.html'+location.search+location.hash);return true}if(location.hash==='#map'||location.hash.startsWith('#lesson/')){location.replace('/chapter-one.html'+location.search+location.hash);return true}return false};
window.addEventListener('hashchange',legacy);
if(!legacy()){
 document.body.classList.add('course-mode','paths-mode');
 const xp=companionXP(),next=nextEvolution(xp);
 const scenes={fundamentals:{title:'Start with the customer experience, connect a service, and understand its data.',nodes:[{id:'experience',kind:'storefront',label:'EXPERIENCE',x:235,y:85,tone:'sage'},{id:'service',kind:'service',label:'SERVICE',x:110,y:225,tone:'lilac'},{id:'data',kind:'database',label:'DATA',x:360,y:235,tone:'peach'}],edges:[{from:'experience',to:'service'},{from:'service',to:'data'}],sequence:[{node:'experience',text:'Understand the need'},{node:'service',text:'Shape the behavior'},{node:'data',text:'Reason about the dependencies'}]},'hard-parts':{title:'Weigh a trade-off between independent services and coordinated data, then test the decision.',nodes:[{id:'choice',kind:'balance',label:'TRADE-OFF',x:235,y:85,tone:'peach'},{id:'service',kind:'service',label:'BOUNDARIES',x:110,y:225,tone:'lilac'},{id:'queue',kind:'queue',label:'COORDINATION',x:360,y:235,tone:'honey'}],edges:[{from:'choice',to:'service'},{from:'choice',to:'queue'},{from:'service',to:'queue',dashed:true}],sequence:[{node:'choice',text:'Identify the competing forces'},{node:'service',text:'Choose a boundary'},{node:'queue',text:'Accept and test the coordination cost'}]}};
 document.querySelector('#app').innerHTML=`<header><nav class="nav shell"><a class="brand" href="/">◇ fieldnotes<span>.</span></a><div class="home-tools"><span class="home-xp">${xp.toLocaleString()} XP across your paths</span><button class="motion-toggle" type="button" aria-label="Pause animations">Ⅱ</button></div></nav></header><main class="paths-main"><section class="paths-intro"><div><div class="eyebrow">Your architecture fieldnotes</div><h1>Where will you <br><em>grow next?</em></h1><p>Start with the foundations. Go deeper into the hard decisions.<br>Two books, one place to learn by doing.</p></div><aside class="home-companion">${renderBot({xp,decorative:false})}<div><strong>${evolutionFor(xp).name}</strong><p>${next?`Next evolution at ${next.xp.toLocaleString()} XP.`:'Your architect companion is fully evolved.'}<br>Your progress travels with you.</p></div></aside></section><div class="mobile-path-picker" aria-label="Choose a path">${Object.values(paths).map((path,i)=>`<button type="button" data-select-path="${path.id}" aria-pressed="${i===0}">${path.shortTitle}</button>`).join('')}</div><section class="learning-paths" aria-label="Choose a learning path">${Object.values(paths).map((path,i)=>{const progress=progressFor(path.id),earned=progress.totalXP(),completed=path.catalog.filter(ch=>progress.chapterXP(ch.number)===100).length,last=lastLocation(path.id);return `<article class="path-card path-${path.id}"><div class="path-card-top"><span>PATH 0${i+1}</span><span>${path.level}</span></div><div class="path-scene">${renderScene(scenes[path.id])}</div><div class="path-card-copy"><div class="eyebrow">${path.tag}</div><h2>${path.title}</h2><p>${path.description}</p><div class="path-facts"><span>${path.count} chapters</span><span>${path.count===24?'Architecture essentials':'Advanced trade-offs'}</span><span>All chapters open</span></div><div class="path-progress"><div><strong>${completed} / ${path.count} completed</strong><span>${earned.toLocaleString()} / ${path.totalXP.toLocaleString()} XP</span></div><progress value="${earned}" max="${path.totalXP}" aria-label="${path.shortTitle} progress"></progress></div>${last?`<p class="path-resume">Pick up at chapter ${last.chapter}: ${path.catalog[last.chapter-1].title}</p>`:'<p class="path-resume">Your next learning adventure starts here.</p>'}<div class="path-actions"><a class="primary" href="${resumeURL(path.id)}">${last?'Resume path':'Explore path'} →</a>${last?`<a class="path-browse" href="${path.entry}">All chapters</a>`:''}</div></div></article>`}).join('')}</section><footer class="paths-footer"><p>Small lessons. Animated systems. Decisions you can explain.</p><p>Progress and reflections are saved on this device. Each book keeps its own chapter record.</p><a href="/illustrations.html">Explore the illustration studio ↗</a></footer></main>`;
 document.querySelectorAll('[data-select-path]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-select-path]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));document.querySelectorAll('.path-card').forEach(card=>card.classList.toggle('mobile-inactive',!card.classList.contains('path-'+button.dataset.selectPath)))});document.querySelector('[data-select-path]').click();
 mountBackup(document.querySelector('.paths-main'));
 startSceneMotion();
}
