import {downloadText} from './downloads.js';
import {appStorage} from './storage.js';
import './style.css';
import './illustrations/illustrations.css';
import { renderScene } from './illustrations/engine.js';
import { bookshop, dimensions } from './illustrations/scenes.js';

const logo = `<svg viewBox="0 0 28 30" fill="none" aria-hidden="true"><path d="M3 22 14 28 25 22V9L14 3 3 9Z" stroke="currentColor" stroke-width="1.5"/><path d="m3 9 11 6 11-6M14 15v13M8.5 6 20 12v6l-6 3-6-3v-6l11-6" stroke="currentColor" stroke-width="1.5"/></svg>`;
const art = renderScene({ ...bookshop, className: 'architecture-svg' });
const roles=[['Make decisions','Set meaningful constraints that protect the system’s goals. Specify a product when it matters; otherwise, leave teams room to choose.'],['Keep analyzing','Revisit the architecture as traffic, teams, and business goals change. A good decision can outlive the context that made it good.'],['Stay curious','Follow relevant technology and industry changes. Evaluate what solves your problem instead of adopting something just because it is new.'],['Check compliance','Use reviews and automated checks to keep implementation aligned with decisions. Handle justified exceptions explicitly.'],['Build breadth','Learn across languages, platforms, and environments. A wider set of experiences helps reveal alternatives and hidden costs.'],['Know the business','Understand domain language, constraints, and priorities. Architecture should help the business succeed, not just look elegant.'],['Work with people','Listen, explain, mentor, and facilitate. An architecture only works when people understand it and can build it together.'],['Navigate the organization','Understand incentives and decision-making power. Negotiate changes with the people who bear their cost.']];
document.querySelector('#app').innerHTML=`
<div class="progress" aria-hidden="true"></div>
<header><nav class="nav shell" aria-label="Main navigation"><a href="/" class="brand">${logo} fieldnotes<span style="color:var(--orange)">.</span></a><div class="nav-links"><a href="#foundations">The foundations</a><a href="#tradeoffs">The trade-offs</a><a href="#checkpoint">Check yourself</a></div><span class="nav-end"><i class="status-dot"></i> Chapter 01 / 24</span></nav></header>
<main class="shell">
<section class="hero"><div><div class="eyebrow"><span class="pill">The interactive edition</span><span class="rule"></span><span>01 — Introduction</span></div><h1>Architecture is<br>more than<br><em>the blueprint.</em></h1><p class="intro">It’s the decisions, the trade-offs, and the reasons behind them. Let’s take the first chapter apart—and build your understanding.</p><div class="hero-actions"><a class="primary" href="#foundations">Explore the chapter <span>↗</span></a><span class="reading-time">◷ &nbsp; 8–12 min exploration</span></div><p class="source-note">Based on <i>Fundamentals of Software Architecture</i><br>Mark Richards & Neal Ford · O’Reilly, 2020 · Chapter 1</p></div><div class="hero-art"><span class="art-label">FIG. 01 &nbsp; A SYSTEM IS A SET OF CHOICES</span><span class="art-live"><i></i> SYSTEM IN MOTION</span>${art}<div class="art-bottom"><span>Connected by intent. Shaped by constraints.</span><span>↗</span></div></div></section>
<div class="concept-strip"><a class="strip-item" href="#foundations"><span class="strip-num">01</span><div><strong>See the whole picture</strong><span>Four dimensions of architecture</span></div></a><a class="strip-item" href="#tradeoffs"><span class="strip-num">02</span><div><strong>Make the trade-off</strong><span>No perfect choices. Better fits.</span></div></a><a class="strip-item" href="#architect"><span class="strip-num">03</span><div><strong>Think like an architect</strong><span>A role beyond writing code</span></div></a><a class="strip-item" href="#rationale"><span class="strip-num">04</span><div><strong>Remember the why</strong><span>Capture the reasoning</span></div></a></div>
<section id="foundations" class="section reveal"><div class="section-heading"><div><div class="eyebrow">01 / The foundations · pp. 3–7</div><h2>A diagram is only the beginning.</h2></div><p class="section-sub">Four dimensions work together to describe an architecture. Explore each layer of the story.</p></div><div class="explorer"><div class="explorer-copy"><div class="tabs" role="tablist" aria-label="Architecture dimensions">${['Structure','Characteristics','Decisions','Principles'].map((x,i)=>`<button class="tab ${i===0?'active':''}" role="tab" id="tab-${i}" aria-controls="concept-panel" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-tab="${i}">${x}</button>`).join('')}</div><div id="concept-panel" role="tabpanel" aria-labelledby="tab-0" tabindex="0"></div></div><div class="explorer-visual"><span class="diagram-caption">A TINY ONLINE BOOKSHOP · TEACHING EXAMPLE</span><div class="dimension-art"></div><p class="diagram-explanation" id="diagram-explanation"></p></div></div></section>
<aside class="law-banner reveal"><div><div class="eyebrow">The first law · p. 19</div><h3>Every architectural choice<br>comes with a trade-off.</h3><p>If you can’t see the cost yet, keep looking.</p></div><span class="balance-mark" aria-hidden="true">⇌</span></aside>
<section id="tradeoffs" class="section reveal"><div class="section-heading"><div><div class="eyebrow">02 / The trade-off lab</div><h2>Better for what, exactly?</h2></div><p class="section-sub">Same system. Different priorities. Change the context and see why the answer changes.</p></div><div class="lab"><div class="lab-controls"><div class="mini-label">Choose your context</div><div class="scenario-switch" role="group" aria-label="Business context"><button class="active" data-scenario="startup" aria-pressed="true">🌱 &nbsp; Small startup</button><button data-scenario="scale" aria-pressed="false">↗ &nbsp; Growing platform</button></div><p id="scenario-description" class="scenario-description"></p><label class="range-label" for="distribution">How much do you split the system? <output id="distribution-value" for="distribution">1 deployable</output></label><input id="distribution" type="range" min="1" max="5" value="1" step="1"/><div class="range-ends"><span>One deployment</span><span>Independent services</span></div></div><div class="lab-result"><div class="mini-label">The consequences of your choice</div><div id="metrics"></div><div class="verdict" id="verdict" aria-live="polite"></div></div></div><p class="teaching-note">Teaching extension · Bars are illustrative, not measurements or universal rankings. Assume separable domains and well-designed boundaries. Splitting services does not automatically improve reliability or delivery speed.</p></section>
<section id="architect" class="section reveal" style="padding-top:10px"><div class="section-heading"><div><div class="eyebrow">03 / The architect’s mindset · pp. 8–12</div><h2>Part technologist. Part people person.</h2></div><p class="section-sub">Eight expectations, whatever your job title.<br>Open a card to see what each looks like.</p></div><div class="roles-grid">${roles.map((r,i)=>`<details class="role"><summary><span class="role-top"><span>0${i+1}</span><span class="role-plus" aria-hidden="true">+</span></span>${r[0]}</summary><p>${r[1]}</p></details>`).join('')}</div><div class="connections"><strong>Architecture doesn’t<br>happen in isolation.</strong><p><b>Engineering practices</b> make qualities testable. <b>Operations</b> shapes what you can run. <b>Process</b> sets the speed of feedback. <b>Data</b> brings its own constraints. Revisit decisions as all four evolve. <span style="font-size:9px">(pp. 13–19)</span></p></div></section>
<section id="checkpoint" class="checkpoint reveal"><div><div class="eyebrow">A moment to connect the dots</div><h2>Can you spot<br>the distinction?</h2><p class="checkpoint-intro">Three quick scenarios. No timer, no pressure.<br>Understanding beats memorization.</p></div><div id="quiz"></div></section>
<section id="rationale" class="section rationale reveal"><div><div class="eyebrow">04 / The second law · pp. 19–20</div><h2>The diagram shows how.<br>The decision explains why.</h2><p>A future teammate can trace your services. They can’t trace your reasoning unless you leave it behind.</p><p>Try a tiny architecture decision record. Capture the context, your choice, and the cost you’re willing to accept. When the context changes, you’ll know what to revisit.</p><p class="teaching-note">Practice extension · This short form is a learning aid, not a template from Chapter 1. Your draft stays in this browser when local storage is available.</p></div><form class="decision-card" id="decision-form"><div class="mini-label">ADR / 001 &nbsp; A decision worth remembering</div><label for="decision">We will…</label><input id="decision" value="Start with a modular monolith" maxlength="220"/><label for="reason">Because…</label><textarea id="reason" maxlength="2000">We are a team of three validating a bookshop. One deployment keeps operations manageable while we learn.</textarea><label for="cost">We accept…</label><textarea id="cost" maxlength="2000">Scaling and releases are shared. We will revisit this when a module needs independent scaling or ownership.</textarea><div class="save-line" id="save-status" aria-live="polite"></div><button class="download" type="submit">Download your decision &nbsp; ↓</button></form></section>
</main><footer><div class="shell footer-inner"><a class="brand footer-brand" href="#">${logo} fieldnotes.</a><p>An independent learning companion, not an official O’Reilly edition.<br>Original paraphrases of Chapter 1 · Interactive examples are educational extrapolations.</p><div class="footer-links"><a href="/chapter-1-summary.md" target="_blank" rel="noopener">Chapter notes ↗</a><a href="#">Back to top ↑</a></div></div></footer>`;

const concepts=[
 {icon:'▧',title:'Structure gives the system its shape.',description:'Layers, microservices, a microkernel: the organizing style describes how the parts fit together. But naming a style doesn’t explain the whole architecture.',example:'A layered bookshop separates the storefront, order logic, and data access.',caption:'The boxes and connections describe structure—not the entire architecture.',nodes:[0,1,2]},
 {icon:'◷',title:'Characteristics define success.',description:'Beyond what the system does, how well must it do it? Performance, availability, and maintainability are architectural goals—not extra features to add later.',example:'Our bookshop should remain responsive during a promotion. We need a measurable target and a way to check it.',caption:'The same boxes can meet very different quality goals. Define and test the goals.',nodes:[0,1]},
 {icon:'⊣',title:'Decisions set the boundaries.',description:'Decisions establish constraints on how a system is built. A justified exception is a variance: it should be reviewed explicitly, not hidden in a shortcut.',example:'The storefront must access books through the service layer, never directly through the database.',caption:'The layer boundary is a rule. Skipping it requires an explicit, justified exception.',nodes:[1,2]},
 {icon:'↗',title:'Principles guide the choices.',description:'A principle expresses a preferred direction rather than an absolute rule. It leaves space for a team to choose a better fit in a particular situation.',example:'Prefer asynchronous notifications after an order. Use a direct response when the customer needs immediate confirmation.',caption:'A preference guides the implementation while allowing context-sensitive choices.',nodes:[1]}
];
function selectTab(index,focus=false){const c=concepts[index];document.querySelectorAll('.tab').forEach((b,i)=>{b.classList.toggle('active',i===index);b.setAttribute('aria-selected',i===index);b.tabIndex=i===index?0:-1;if(focus&&i===index)b.focus()});const panel=document.querySelector('#concept-panel');panel.setAttribute('aria-labelledby',`tab-${index}`);panel.innerHTML=`<div class="content-swap"><div class="concept-icon" aria-hidden="true">${c.icon}</div><h3>${c.title}</h3><p class="concept-description">${c.description}</p><div class="example"><b>In our bookshop</b>${c.example}</div></div>`;document.querySelectorAll('.system-node').forEach((n,i)=>n.classList.toggle('highlight',c.nodes.includes(i)));document.querySelector('#diagram-explanation').textContent=c.caption;document.querySelector('.dimension-art').innerHTML=renderScene(dimensions[index]);}
document.querySelectorAll('.tab').forEach((b,i)=>{b.addEventListener('click',()=>selectTab(i));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%4;if(e.key==='ArrowLeft')n=(i+3)%4;if(e.key==='Home')n=0;if(e.key==='End')n=3;if(n!==undefined){e.preventDefault();selectTab(n,true)}})});selectTab(0);
let scenario='startup';const slider=document.querySelector('#distribution');
function updateLab(){let n=Number(slider.value);document.querySelector('#distribution-value').textContent=`${n} deployable${n>1?'s':''}`;document.querySelector('#scenario-description').textContent=scenario==='startup'?'Three engineers. An idea to validate. Limited operational capacity. Your priority is learning quickly with a system the team can confidently run.':'Four product teams. Uneven traffic across features. Dedicated operational support. Independent ownership and selective scaling now matter more.';const metrics=[['Independent scaling',18+n*14,'More flexibility',false],['Operational complexity',10+n*16,'More work',true],['Coordination overhead',scenario==='startup'?16+n*14:94-n*12,scenario==='startup'?'Across services':'Across teams',true]];document.querySelector('#metrics').innerHTML=metrics.map(([label,value,hint,cost])=>`<div class="metric ${cost?'cost':''}"><div class="metric-title"><span>${label}</span><span>${hint}</span></div><div class="bar" role="img" aria-label="${label}: ${value} out of 100, illustrative"><i style="width:${value}%"></i></div></div>`).join('');const verdict=scenario==='startup'?(n<=2?['A reasonable starting point.','One deployment keeps the operating burden low. You accept shared releases and scaling. Keep internal module boundaries clear so you can change later.']:['More freedom, more to operate.','Independent services add networks, deployments, and failure modes. For three people, that cost may outweigh the scaling benefit. What evidence justifies it?']):(n>=3?['Independence may earn its keep.','Teams can release and scale separate capabilities. You accept distributed troubleshooting and stronger automation requirements. Check that ownership and data boundaries really align.']:['Simple deployment, shared constraints.','Fewer moving parts are easier to operate. But shared releases and scaling may now create bottlenecks for separate teams. Measure those bottlenecks before splitting.']);document.querySelector('#verdict').innerHTML=`<strong>${verdict[0]}</strong>${verdict[1]}`;}
slider.addEventListener('input',updateLab);document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{scenario=b.dataset.scenario;document.querySelectorAll('[data-scenario]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});updateLab()}));updateLab();
const questions=[{q:'“Only the service layer may access the database.” What is this?',options:['A structure','An architecture decision','A design principle'],answer:1,explain:'This is a construction rule. A principle would express a preference; a structure would describe how the parts are organized.'},{q:'A teammate says, “Microservices are always better.” What is the most useful response?',options:['Yes, more services mean more reliability.','No, a monolith is always simpler to change.','Better for which goals, and at what cost?'],answer:2,explain:'Styles have trade-offs. Team size, operational maturity, quality goals, and domain boundaries all affect whether a style fits.'},{q:'The system diagram survives, but the team’s reasoning is lost. What is missing?',options:['The context and trade-offs behind the choices','A more detailed list of technologies','More boxes and arrows'],answer:0,explain:'A diagram records shape. The rationale preserves why a decision made sense, the alternatives, and when the decision should be reconsidered.'}];let qi=0,answered=false,score=0;
function renderQuiz(){const q=questions[qi];answered=false;document.querySelector('#quiz').innerHTML=`<div class="mini-label">Question 0${qi+1} / 03</div><h3 class="quiz-question">${q.q}</h3><div class="quiz-options">${q.options.map((x,i)=>`<button class="quiz-option" data-answer="${i}"><span class="option-letter">${'ABC'[i]}</span>${x}</button>`).join('')}</div><div class="quiz-feedback" aria-live="polite"></div><div id="quiz-action"></div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>{if(answered)return;answered=true;const correct=+b.dataset.answer===q.answer;if(correct)score++;document.querySelectorAll('[data-answer]').forEach(x=>{x.setAttribute('aria-disabled','true');if(+x.dataset.answer===q.answer)x.classList.add('correct')});if(!correct)b.classList.add('incorrect');document.querySelector('.quiz-feedback').textContent=`${correct?'Exactly.':'Not quite. '+q.options[q.answer]+' is the answer.'} ${q.explain}`;document.querySelector('#quiz-action').innerHTML=`<button class="quiz-next">${qi<2?'Next question →':'See your takeaway →'}</button>`;document.querySelector('.quiz-next').addEventListener('click',()=>{if(qi<2){qi++;renderQuiz();document.querySelector('.quiz-option').focus()}else{document.querySelector('#quiz').innerHTML=`<div class="mini-label">Chapter checkpoint complete</div><h3 class="quiz-question">${score} of 3 on your first try.</h3><p class="quiz-feedback">Architecture combines shape, goals, rules, and guidance. Every choice has a cost. Keep the reasoning with the decision.</p><button class="quiz-next">Try again ↻</button>`;document.querySelector('.quiz-next').focus();document.querySelector('.quiz-next').addEventListener('click',()=>{qi=0;score=0;renderQuiz();document.querySelector('.quiz-option').focus()})}})}));}renderQuiz();
const fields=['decision','reason','cost'];try{const stored=JSON.parse(appStorage.getItem('fieldnotes-adr-v1'));if(stored)fields.forEach(id=>{if(typeof stored[id]==='string')document.getElementById(id).value=stored[id]})}catch{}
fields.forEach(id=>document.getElementById(id).addEventListener('input',()=>{try{appStorage.setItem('fieldnotes-adr-v1',JSON.stringify(Object.fromEntries(fields.map(id=>[id,document.getElementById(id).value]))));document.querySelector('#save-status').textContent='Draft saved on this device.'}catch{document.querySelector('#save-status').textContent='Saving is unavailable. Export to keep your draft.'}}));
document.querySelector('#decision-form').addEventListener('submit',async e=>{e.preventDefault();const [d,r,c]=fields.map(id=>document.getElementById(id).value);try{await downloadText('architecture-decision-001.md',`# ADR 001: ${d}\n\nStatus: Learning draft\n\n## Context and rationale\n${r}\n\n## Accepted consequences and revisit trigger\n${c}\n`);document.querySelector('#save-status').textContent='Decision record exported.'}catch{document.querySelector('#save-status').textContent='Export was not completed. Your draft is still here.'}});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));window.addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=`${max>0?scrollY/max*100:0}%`},{passive:true});

import('./quest.js');

import { startSceneMotion } from './illustrations/motion.js';
startSceneMotion();
