import {companionXP} from './progress.js';
import {firstStoryIntro} from './chapters/first-story.js';
import { motionEnabled } from './illustrations/motion-preference.js';
import { chapterState, chapterXP, totalXP, awardMission } from './progress.js';
import { renderBot, evolutionFor } from './illustrations/sidekick.js';
import { renderScene, renderFigure, highlightScene } from './illustrations/engine.js';
import { firstStoryScene, deployments, engineering, operations, feedback, data, rationale, checkpoint } from './illustrations/scenes.js';
const $ = (s) => document.querySelector(s);
const reduced = () => !motionEnabled();
const bot = renderBot({xp:companionXP()});
const missions=[['explore','Explore','#foundations'],['sort','Classify','#card-challenge'],['lab','Experiment','#tradeoffs'],['quiz','Reflect','#checkpoint'],['record','Decide','#rationale']];
const earned=new Set(Object.keys(chapterState(1).missions).filter(key=>chapterState(1).missions[key]===true));
const dock=document.createElement('aside');dock.className='quest-dock';dock.setAttribute('aria-label','Learning quest progress');dock.innerHTML=`<div class="quest-emblem" title="Pip evolves as you earn XP">${renderBot({xp:companionXP(),decorative:false})}</div><div class="quest-level"><b id="quest-rank">Curious explorer</b><span><strong id="xp">${totalXP()}</strong> / 2,400 XP <span class="visit-note">· whole book</span></span></div><div class="quest-track"><div class="quest-meter"><i></i></div><div class="mission-links">${missions.map(([id,name,href])=>`<a href="${href}" data-mission="${id}"><span>○</span> ${name}</a>`).join('')}</div></div><button class="motion-toggle" type="button" aria-pressed="false" aria-label="Pause decorative animations">Ⅱ</button>`;document.body.append(dock);
const toast=document.createElement('div');toast.className='quest-toast';toast.setAttribute('role','status');document.body.append(toast);
let toastTimer;
function award(id,message){if(earned.has(id))return;earned.add(id);awardMission(1,id);window.dispatchEvent(new CustomEvent('fieldnotes:earned',{detail:id}));const xp=totalXP();$('#xp').textContent=xp;document.querySelectorAll('.hero-bot,.guide-bot,.quest-emblem').forEach(el=>{el.innerHTML=renderBot({xp:companionXP(),decorative:!el.classList.contains('quest-emblem')});el.classList.remove('pip-evolve');void el.offsetWidth;el.classList.add('pip-evolve')});window.dispatchEvent(new CustomEvent('fieldnotes:pip',{detail:xp}));$('#quest-rank').textContent=evolutionFor(companionXP()).name;$('.quest-meter i').style.width=chapterXP(1)+'%';const link=$(`[data-mission="${id}"]`);link.classList.add('earned');link.querySelector('span').textContent='✓';toast.textContent=`+20 XP · ${message}${chapterXP(1)===100?' · Chapter missions complete!':''}`;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3800);celebrate();}
function celebrate(){if(reduced()||document.body.classList.contains('motion-paused'))return;const burst=document.createElement('div');burst.className='celebration';burst.setAttribute('aria-hidden','true');for(let i=0;i<22;i++){const bit=document.createElement('i');bit.style.cssText=`--x:${(Math.random()-.5)*650}px;--y:${-130-Math.random()*250}px;--r:${Math.random()*650}deg;--delay:${Math.random()*.15}s;background:${['#f47c55','#ad98ed','#c8d99c','#f8d87b'][i%4]}`;burst.append(bit)}document.body.append(burst);setTimeout(()=>burst.remove(),1800);}

$('.hero .pill').textContent='Learn by playing';$('.hero .intro').textContent=firstStoryIntro;$('.hero .primary').innerHTML='Start your quest <span>↗</span>';$('.reading-time').textContent='5 missions · 100 XP';
$('.hero-art').insertAdjacentHTML('beforeend',`<div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="floating-chip chip-one">◇ &nbsp; A little structure</span><span class="floating-chip chip-two">✦ &nbsp; A lot of “why”</span><div class="hero-bot">${bot}</div><button class="send-order" type="button">▶ &nbsp; Send a book order</button><div class="order-status" role="status">Your bookshop is ready. Try it!</div>`);
$('.art-label').textContent='YOUR FIRST SYSTEM / THE BOOKSHOP';$('.art-bottom').remove();
let running=false;
$('.send-order').addEventListener('click',async()=>{if(running)return;running=true;$('.architecture-svg').dataset.manual='true';$('.architecture-svg').querySelectorAll('.iso-processing').forEach(n=>n.classList.remove('iso-processing'));$('.send-order').disabled=true;const steps=[['Pip watches a reader order a book.','interface'],['Pip follows the order service’s business rules.','orders'],['Pip checks the saved order and reserved stock.','data'],['Order confirmed. Pip can name each responsibility.',null]];for(const [text,index] of steps){$('.order-status').textContent=text;highlightScene($('.architecture-svg'),index?[index]:[]);await new Promise(r=>setTimeout(r,reduced()?180:950))}$('.send-order').disabled=false;$('.send-order').innerHTML='↻ &nbsp; Send another order';running=false;$('.architecture-svg').dataset.manual='false';});
const visited=new Set([0]);document.querySelectorAll('.tab').forEach((el,i)=>el.addEventListener('click',()=>{visited.add(i);if(visited.size===4)award('explore','All four dimensions explored')}));$('.tabs').addEventListener('keydown',()=>{const active=$('.tab[aria-selected="true"]');visited.add(Number(active.dataset.tab));if(visited.size===4)award('explore','All four dimensions explored')});
const challenge=document.createElement('section');challenge.id='card-challenge';challenge.className='sorting-challenge section';challenge.innerHTML=`<div class="challenge-guide"><div class="guide-bot">${bot}</div><div><div class="eyebrow">Mini mission / +20 XP</div><h2>Put the idea in its place.</h2><p>Pip drops four bookshop notes. Help sort their shape, goal, rule, and preference.</p></div></div><div class="sorting-board"><div class="sort-progress"><span>NOTE <b id="sort-number">01</b> / 04</span><div id="sort-dots">${[0,1,2,3].map(()=>'<i></i>').join('')}</div></div><div id="sort-card" class="sort-card"></div><div class="sort-targets" role="group" aria-label="Classify this architecture note">${['Structure','Characteristics','Decisions','Principles'].map((name,i)=>`<button type="button" data-category="${i}"><span>${['▧','◷','⊣','↗'][i]}</span>${name}</button>`).join('')}</div><p id="sort-feedback" role="status">Choose a category. Mistakes are part of the mission.</p><button class="sort-next" type="button" hidden>Next note →</button></div>`;$('#foundations').after(challenge);
const cards=[['“Organize the bookshop into presentation, business, and data layers.”',0,'That describes the arrangement of the system. Structure tells us how the parts fit together.'],['“The catalogue should respond within our agreed latency target.”',1,'That is a quality goal. It describes how well the system must work, rather than a business feature.'],['“The storefront must not query the database directly.”',2,'“Must not” sets a construction rule. A justified exception needs an explicit review.'],['“Prefer asynchronous delivery of order notifications.”',3,'“Prefer” gives direction while allowing a different choice when the context calls for it.']];let card=0,solved=false;
function showCard(){solved=false;$('#sort-number').textContent='0'+(card+1);$('#sort-card').textContent=cards[card][0];$('#sort-card').classList.remove('card-arrive');void $('#sort-card').offsetWidth;$('#sort-card').classList.add('card-arrive');$('#sort-feedback').textContent='Choose a category. Mistakes are part of the mission.';$('.sort-next').hidden=true;document.querySelectorAll('[data-category]').forEach(b=>{b.disabled=false;b.classList.remove('right','wrong')})}
document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{if(solved)return;const correct=Number(b.dataset.category)===cards[card][1];b.classList.remove('wrong');void b.offsetWidth;if(!correct){b.classList.add('wrong');$('#sort-feedback').textContent='Try another category. Is this a shape, a quality goal, a rule, or a preference?';return}solved=true;b.classList.add('right');$('#sort-feedback').textContent=cards[card][2];document.querySelectorAll('#sort-dots i')[card].classList.add('done');document.querySelectorAll('[data-category]').forEach(x=>x.disabled=true);$('.sort-next').hidden=false;if(card===3){award('sort','Four ideas, four dimensions');$('.sort-next').textContent='Replay the notes ↻'}$('.sort-next').focus()}));$('.sort-next').addEventListener('click',()=>{card=(card+1)%4;if(card===0){document.querySelectorAll('#sort-dots i').forEach(x=>x.classList.remove('done'));$('.sort-next').textContent='Next note →'}showCard();$('[data-category]').focus()});showCard();
// The picture changes with the simulator, making the distribution cost tangible.
$('.lab-controls').insertAdjacentHTML('beforeend',`<div class="service-playground" aria-label="Illustrative deployment topology"><div class="playground-label"><span>LIVE SYSTEM SKETCH</span><span id="wire-count"></span></div><div class="deployment-world"></div><p>Pip gains independence—and more connections to manage.</p></div>`);
function drawSystem(){const n=Number($('#distribution').value);$('.deployment-world').innerHTML=renderScene(deployments(n));$('#wire-count').textContent=`${n} deployment${n>1?'s':''}`;}

const contexts=new Set(['startup']);let adjusted=false;$('#distribution').addEventListener('input',()=>{adjusted=true;drawSystem();checkLab()});document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{contexts.add(b.dataset.scenario);checkLab()}));function checkLab(){if(adjusted&&contexts.size===2)award('lab','Compared the same choice in two contexts')}drawSystem();$('.lab-controls').insertAdjacentHTML('beforeend','<p class="mission-hint">✦ Earn 20 XP: move the slider and compare both contexts.</p>');
// Small editorial illustrations for each responsibility, drawn in a shared visual language.
const drawings=['<path d="M20 47V17h28l-8 9 8 9H20"/>','<circle cx="30" cy="28" r="13"/><path d="m40 39 11 11M22 30l6-6 7 3"/>','<path d="m19 43 9-27 10 18 13-6-9 22Z"/><path d="m43 15 3-5m6 11 5-1"/>','<path d="m32 10 20 8-3 22-17 13-17-13-3-22Z"/><path d="m23 31 7 7 12-15"/>','<rect x="13" y="26" width="12" height="23" rx="2"/><rect x="27" y="15" width="12" height="34" rx="2"/><path d="m43 19 11-3 7 30-11 3Z"/>','<path d="M12 25h41v25H12Z M24 25v-9h16v9M12 34h41M28 32v7h10v-7"/>','<circle cx="23" cy="23" r="9"/><circle cx="45" cy="26" r="7"/><path d="M8 50v-7c0-14 30-14 30 0v7m1-14c10-4 19 2 19 11v3"/>','<path d="M15 47V17h34v30M24 47V31h16v16M10 48h45M23 24h3m11 0h3"/>'];document.querySelectorAll('.role').forEach((el,i)=>{el.querySelector('summary').insertAdjacentHTML('afterbegin',`<svg class="role-illustration" viewBox="0 0 66 64" fill="none" aria-hidden="true"><circle cx="33" cy="32" r="29" fill="${['#e8def6','#f9e3b7','#dae9d4','#f6d8ca'][i%4]}"/> <g stroke="#625574" stroke-width="2.3" stroke-linecap="round" stroke-linejoin="round">${drawings[i]}</g></svg>`)});
$('#quiz').addEventListener('click',()=>{if($('#quiz').textContent.includes('on your first try.'))award('quiz','Reflected on all three scenarios')});$('#decision-form').addEventListener('submit',()=>{if(['decision','reason','cost'].every(id=>$('#'+id).value.trim()))award('record','Captured a decision and its why')});
$('.checkpoint-intro').insertAdjacentHTML('beforeend','<span class="mission-hint">✦ Finish all three reflections to earn 20 XP.</span>');
$('.law-banner').insertAdjacentHTML('beforeend',`<svg class="scale-illustration" viewBox="0 0 220 150" aria-hidden="true"><ellipse cx="110" cy="136" rx="74" ry="8" fill="#141c19" opacity=".4"/><path d="M110 32v96M80 131h60" stroke="#e8dfba" stroke-width="6" stroke-linecap="round"/><g class="scale-beam"><path d="m32 43 156-10" stroke="#e8dfba" stroke-width="5" stroke-linecap="round"/><path d="m44 43-22 51h44L44 43m132-10-22 51h44l-22-51" fill="none" stroke="#bab5bd" stroke-width="2"/><path d="M20 94h48q-24 32-48 0" fill="#ed9a76"/><path d="M152 84h48q-24 32-48 0" fill="#b9a5e1"/></g><circle cx="110" cy="37" r="9" fill="#f4d987"/></svg>`);

// Larger chapter illustrations share the same renderer as the hero and live simulator.
const ecosystems = [
  [engineering, '01 / Engineering practices', 'Pip changes an order rule.', 'An automated check connects code to the architectural goal.', 'sage'],
  [operations, '02 / Operations', 'Pip rehearses a failed deployment.', 'Observation and recovery reveal what the platform can actually support.', 'lilac'],
  [feedback, '03 / Process', 'Pip watches the new release.', 'Fast feedback sends a mistaken assumption back to the drawing board.', 'honey'],
  [data, '04 / Data', 'Pip changes shared book data.', 'Two capabilities feel the effect; ownership matters alongside code.', 'peach'],
];
$('.connections').outerHTML=`<div class="ecosystem"><div class="ecosystem-heading"><h3>One architecture. A connected world.</h3><p>Pip’s blueprint meets code, operations, feedback, and shared data. Each changes the choices. (pp. 13–19)</p></div><div class="ecosystem-grid">${ecosystems.map(([scene,label,title,caption,theme],i)=>renderFigure(firstStoryScene(scene,['engineering','operations','feedback','data'][i],totalXP()),{label,caption:title+' '+caption,theme})).join('')}</div></div>`;
$('#rationale > div').insertAdjacentHTML('beforeend',renderFigure(firstStoryScene(rationale,'rationale',totalXP()),{label:'Pass the reasoning forward',caption:'Pip leaves the context a future teammate cannot infer from boxes.',theme:'honey',className:'rationale-art'}));
$('#checkpoint > div').insertAdjacentHTML('beforeend',`<div class="checkpoint-art">${renderScene(firstStoryScene(checkpoint,'checkpoint',totalXP()))}</div>`);

$('#quest-rank').textContent=evolutionFor(companionXP()).name;
import('./course.js');
